### ISSUE TITLE
Task: .NET Standard and Core support

### ISSUE THREAD

**Issue by paulushub** [ElinamLLC/SharpVectors#100]
Move the projects to the new SDK format, targeting multiple versions (now only .NET 4) and platforms.
The common components are mostly ready for the cross-platform support.
- SharpVectors.Core
- SharpVectors.Css
- SharpVectors.Dom
- SharpVectors.Model

**Comment by wyshmily** [comment]
Thanks a lot for this great project. Just wonder is there a schedule on netcore ( 3.0 ) support ?

**Comment by paulushub** [comment]
Thanks for the interest. Still trying to resolve the JavaScript package to use for the scripting support in the SharpVectors.
The initial choice was ClearScript (well-documented and well-designed API), but this will not work on NetCore.
Currently, evaluating Jint, it is not well documented. Not even a single sample application is available in the repository, so trying to rely on snippets on the web.

Alternatively, I might create a common scripting interfaces or API (as part of SharpVectors.Core) and provide platform specific implementation. WPF/WinForms/Windows implementation can use the ClearScript without the V8.

**Comment by paulushub** [comment]
@wyshmily Which Core version will your prefer? Core 3, Core 3.1 or both?

**Comment by dojo90** [comment]
`.NET Core 3.1` because 3.0 is already discontinued and 3.1 is an LTS version.

![grafik](https://user-images.githubusercontent.com/17551597/81784804-b0ad3700-94fd-11ea-816b-67d69421bd63.png)

(https://dotnet.microsoft.com/platform/support/policy/dotnet-core)
