### ISSUE TITLE
Display SVG image from Stream in WPF

### ISSUE THREAD

**Issue by DanielPeinhopf** [ElinamLLC/SharpVectors#101]
Is it possible to display an svg image in WPF based on stream instead of files?
Are there any examples?

**Comment by paulushub** [comment]
@DanielPeinhopf Yes, it is possible. Use the StreamSvgConverter. See the StreamSvgConverterSample or StreamSvgConverterSampleVB sample in the TutorialSamples direction for examples.

It that is not what you need, then specify your requirements and I will add them for you where possible.

**Comment by DanielPeinhopf** [comment]
Ok, thank you. I've already seen the StreamSvgConverter Sample but this converter is generating a raster image. The <SvgViewbox /> instead is generating a xaml path.
What i want to achieve is to do exactly the same as the SvgViewbox but load the svg from a stream instead of a file so that the SvgViewbox control can be resized without seeing pixels.

**Comment by paulushub** [comment]
Some facts:
1. All the svg converters (derive for SvgConverter) produce only DrawingGroup representing your  Svg source. This can be converted into DrawingImage/BitmapSource or save to a file as XAML.
2. You do not need MemoryStream for the StreamSvgConverter, the sample is trying to demonstrate a stream source in the simplest way so the use for the MemoryStream, any Stream object can be used.

Now, I get your need/requirement. I will add Stream support to the SvgViewbox and other controls. That will better meet your needs.

**Comment by paulushub** [comment]
@DanielPeinhopf Please review the updates and give me some feedback, where possible. Check the readme file for the updated samples to see the current state of the samples.

https://github.com/ElinamLLC/SharpVectors/tree/master/TutorialSamples/ControlSamplesWpf
