### ISSUE TITLE
Inkscape image fails to render

### ISSUE THREAD

**Issue by DaveInCaz** [ElinamLLC/SharpVectors#103]
The attached SVG does not render in SharpVectors. I've tried it using SharpVectors in my own app, and also in the WPF SVG TestBox. It just shows up blank.

Inkscape is happy to render it (as shown in second attachment). Plenty of other Inkscape SVG files have worked fine.

Thanks!

[polyline_ortho_tool.zip](https://github.com/ElinamLLC/SharpVectors/files/3418282/polyline_ortho_tool.zip)

![image](https://user-images.githubusercontent.com/18285074/61647076-8e021700-ac7a-11e9-9472-11a35a023536.png)

**Comment by paulushub** [comment]
@DaveInCaz Thanks for the information. I have tested it, it is actually rendered but out of view. Inkscape is a drawing canvas so you will see it but if you try viewing in any browser you will get the same result; partly visible if you maximized the browser window.

To see the problem, make sure the "**Ignore SVG Root Viewbox**" option is checked in the  **Settings** tab of the WPF SVG TestBox and click the Convert button again. The image will be rendered in view.

**Comment by DaveInCaz** [comment]
@paulushub  thanks for looking into this. That makes sense. I also see now that in Inkscape if I force it to redefine the viewbox that will solve the issue too. The easiest way to do that is in the documetn settings, use the "Resize page to drawing or selection".
