### ISSUE TITLE
Rendered text position differs from Inkscape original

### ISSUE THREAD

**Issue by DaveInCaz** [ElinamLLC/SharpVectors#104]
I have an example where text is not rendering in SharpVectors in the same position as in the original Inkscape document. I've pasted screenshots and also attached the SVG file.

This is being included in XAML like so:

`<Image Source="{svgc:SvgImage Source=Images/sitesample.svg}"/>`

Original Inkscape rendering:
![image](https://user-images.githubusercontent.com/18285074/62079884-954a9700-b21d-11e9-879b-b8caab81fc3b.png)

[sitesample.zip](https://github.com/ElinamLLC/SharpVectors/files/3444158/sitesample.zip)

Rendered output:
![image](https://user-images.githubusercontent.com/18285074/62079659-2d944c00-b21d-11e9-82c1-c570575d918a.png)

Note that it is only the white-colored text which has moved, the black lettering appears unchanged.

Thank you!

**Comment by paulushub** [comment]
Thanks for reporting, looking into it now. 
The GDI+ gets the text position right but will not render the background image. 
The WPF gets the text position wrong but renders the background image.

**Comment by paulushub** [comment]
@DaveInCaz I have provided a fix with the d59d45e30b18cb11571d91bd77cebbdf089b260e commit.

The manual text-alignment for middle alignment fails in this case of multiple text-spans, with each specifying a position.
Still planning a more complete text rendering, but the current fix seems to be working with the test suite too.
Please verify this fix, thank you.

**Comment by DaveInCaz** [comment]
We're still stuck in VS2015 and it looks like your source uses newer C# language features, so I can't build & test from source, unfortunately.

**Comment by paulushub** [comment]
I understand, if you are working in the enterprise, for instance, you do not have access to the community editions, which I am currently using at home.
Sorry, I have being trying to avoid the use of the newer C# features. I will test and resolve anything that might have slipped in. 
However, I'm planning to move to the new SDK project format to support the .NET Core platform too so for each commit, I will update the build outputs.
If you have suggestions as to how to make things easier, please let me know. For development, you might need to debug the codes, so I will look into how best to support VS2015.

**Comment by DaveInCaz** [comment]
Actually I think this is more my limitation than yours... I don't think you should downgrade the code to support too-old versions (4 years...)  The specific issue I think was an expression-bodied get.

I may actually have a way to build in VS2019 which I will try. If that works then even though the rest of my project is 2015 I can probably test the fix.

**Comment by paulushub** [comment]
@DaveInCaz Sorry for the delay, I have replaced all the C# 7+ syntax, the codes will now compile under C# 6 or VS2015.

**Comment by paulushub** [comment]
The nuget package is now available with these updates.
