### ISSUE TITLE
Wrong position of image embedded in SVG

### ISSUE THREAD

**Issue by Suplanus** [ElinamLLC/SharpVectors#105]
I have this SVG ([Test.zip](https://github.com/ElinamLLC/SharpVectors/files/3532915/Test.zip)):
![image](https://user-images.githubusercontent.com/2002916/63568572-f132e200-c575-11e9-8f1e-3071a5b8ea73.png)

If i import it in my WPF application, the embedded image have the wrong position. I think it is on Y-End and not on Y-Start:
![image](https://user-images.githubusercontent.com/2002916/63568636-3820d780-c576-11e9-9eac-68997cae8100.png)

```csharp
WpfDrawingSettings settings = new WpfDrawingSettings();
settings.IncludeRuntime = true;
settings.TextAsGeometry = false;
FileSvgReader converter = new FileSvgReader(settings);
DrawingGroup drawing = converter.Read(@"\\Mac\Home\Downloads\Test\PageMacro1.svg");
if (drawing != null)
{
  svgImage.Source = new DrawingImage(drawing);
}
```

**Comment by paulushub** [comment]
@Suplanus Sorry, this was a long reported issue (#30)  with the WPF rendering but previous attempts were breaking existing tests.
The issue is now resolved and codes committed, please verify this update.

**Comment by Suplanus** [comment]
You are the best.
Give me some time to look into it!

**Comment by Suplanus** [comment]
You are great 😘
