### ISSUE TITLE
Strong Name signing the NuGet

### ISSUE THREAD

**Issue by Suplanus** [ElinamLLC/SharpVectors#108]
In some cases I only could use strong named DLLs. Would love to see this in the NuGet.

https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md

Thanks for your great work!

**Comment by paulushub** [comment]
Verified that all the assemblies have strong names. Currently, I cannot afford the certificate required for NuGet signing. We will welcome any sponsor!!!
