### ISSUE TITLE
MinZoom

### ISSUE THREAD

**Issue by Suplanus** [ElinamLLC/SharpVectors#109]
I want that the zoom can not be less than 1.
So the image should be uniform if the user zoom out.

I set this values:

```xml
MinZoomY="1"
MinZoomX="1"
```

But if zoom the offset is still set and the image is moving.

So I do this workaround:

```csharp
private void ZoomAndPanControl_OnMouseWheel(object sender, MouseWheelEventArgs e)
{
  if (ZoomAndPanControl.ZoomX < 1.0 || ZoomAndPanControl.ZoomY < 1.0)
  {
    ZoomAndPanControl.Reset();
  }
}
```

Is this the best way? Or would it be great to have a property for this?

**Comment by paulushub** [comment]
`MinZoomY` and `MinZoomX` are not defined properties of the zoom control. To restrict the minimum zoom scale to 1.0, set the `MinContentScale` to 1.0. Similarly, if you want to control the maximum zoom scale, set the `MaxContentScale` property. `zoomAndPanControl.MinContentScale  = 1.0`.

Also, see how these properties are used in the samples, like in `DrawingPage.xaml.cs` in the `WpfTestSvgSample`.
```
private void OnCanZoomIn(object sender, CanExecuteRoutedEventArgs e)
{
    if (zoomPanControl == null)
    {
        e.CanExecute = false;
        return;
    }
    e.CanExecute = zoomPanControl.ContentScale < zoomPanControl.MaxContentScale;
}

private void OnCanZoomOut(object sender, CanExecuteRoutedEventArgs e)
{
    if (zoomPanControl == null)
    {
        e.CanExecute = false;
        return;
    }
    e.CanExecute = zoomPanControl.ContentScale > zoomPanControl.MinContentScale;
}
```
