### ISSUE TITLE
FileSvgReader.Read(Stream) throwing Uri exception

### ISSUE THREAD

**Issue by mmatriccino** [ElinamLLC/SharpVectors#110]
An exception occurs in SvgDocument.GetNodeByUri() when the svg has a marker uri that starts with a double quote.  It looks like there are some .Trim calls that are not trimming quotes and are looking for the '#' character in the first position of the Url/Uri.  SvgElement.ResolveUri() and WpfRendering.CreateByUri() also have url.Trim() calls.  These Trim() calls can be changed to include characters, for example: url = url.Trim(new char[]{ '\"', ' ', '\''});

**Comment by paulushub** [comment]
Thanks for reporting. Please post a sample SVG for testing.

**Comment by mmatriccino** [comment]
[0_g2emrupxrcm_0_6.zip](https://github.com/ElinamLLC/SharpVectors/files/3628309/0_g2emrupxrcm_0_6.zip)
