### ISSUE TITLE
Next Nuget Release Request with an existing fix 

### ISSUE THREAD

**Issue by sanmut** [ElinamLLC/SharpVectors#113]
Hi, 
Thank you for this wonderful library. We are running into an intermittent failure with the exception: 
```
System.ArgumentException: An item with the same key has already been added
```
 in `SharpVectors.Dom.Css.CssPrimitiveRgbValue.IsColorName` (file: 
 `Source/SharpVectorCss/Css/CssPrimitiveRgbValue.cs`). 

I see that this was already reported in issue #99 and has been fixed in b75dfc352a95f7621aee66344bb160b6743825. Would it be possible for you to push a new nuget release that includes this commit? Thank you for the great work maintaining this.

**Comment by paulushub** [comment]
The nuget package is now available. Thanks for the support.

**Comment by sanmut** [comment]
Thank you very much for the quick support. Appreciate your help.
