### ISSUE TITLE
FileSVGReader failing for simple SVG with percentage based size

### ISSUE THREAD

**Issue by atmgrifter00** [ElinamLLC/SharpVectors#116]
If you have an SVG file with the following contents:

```
<svg version="1.1" baseProfile="full" xmlns="http://www.w3.org/2000/svg">
<rect width="100%" height="100%" fill="red"/>
</svg>
```

and try to load that using the FileSVGReader, then the DrawingGroup it produces will be empty. Additionally, if the SVG file was instead:

```
<svg version="1.1" baseProfile="full" xmlns="http://www.w3.org/2000/svg">
<rect width="100%" height="100%" fill="red"/>
<circle cx="80" cy="80" r="80" fill="green"/>
</svg>
```

you will still not get a Rectangle as part of the rendered results. It will just be the circle.

**Comment by paulushub** [comment]
@atmgrifter00 Are you defining a window size (with the `SvgWindow` object)?

**Comment by atmgrifter00** [comment]
This is the code at play, and the resulting produced 'Drawing' is simply assigned to the 'Source' of an Image widget.

```
                var wpfSettings = new WpfDrawingSettings();
                wpfSettings.CultureInfo = wpfSettings.NeutralCultureInfo;
                using (var textReader = new StringReader(ImageData))
                {
                    using (var fileReader = new FileSvgReader(wpfSettings))
                    {
                        fileReader.SaveXaml = false;
                        fileReader.SaveZaml = false;
                        var drawing = fileReader.Read(textReader);
                        drawing.Freeze();
                        Drawing = drawing;
                    }
                }
```

So, 'ImageData' here is the stringified version of the SVG I mentioned above.

**Comment by paulushub** [comment]
The result is expected. SVG is designed for the browser, which offers a drawing area defined by the container such as a div-tag or the whole browser client area.
If you specify the lengths in percentage, you are referencing the drawing area dimensions.
Any of the following will produce a red rectangle...
```csharp
var wpfSettings = new WpfDrawingSettings();
wpfSettings.CultureInfo = wpfSettings.NeutralCultureInfo;
using (var textReader = new StringReader(ImageData))
{
    using (var fileReader = new FileSvgReader(wpfSettings))
    {
        fileReader.SaveXaml = false;
        fileReader.SaveZaml = false;
        var svgWnd = fileReader.SvgWindow;

        svgWnd.InnerHeight = 400;
        svgWnd.InnerWidth = 400;

        var drawing = fileReader.Read(textReader);
        drawing.Freeze();
        _drawing = drawing;
    }
}
```
```csharp
var wpfSettings = new WpfDrawingSettings();
wpfSettings.PixelHeight = 400;
wpfSettings.PixelWidth = 400;
wpfSettings.CultureInfo = wpfSettings.NeutralCultureInfo;
using (var textReader = new StringReader(ImageData))
{
    using (var fileReader = new FileSvgReader(wpfSettings))
    {
        fileReader.SaveXaml = false;
        fileReader.SaveZaml = false;
        var svgWnd = fileReader.SvgWindow;

        var drawing = fileReader.Read(textReader);
        drawing.Freeze();
        _drawing = drawing;
    }
}
```
Initially, `SvgWindow`, which is an abstract class, the WPF implementation is WpfSvgWindow, defined a default dimension to prevent such issues, but it was giving problems to others so it was removed.

The other way round is to specify the dimension in the SVG itself as below:
```xml
<svg version="1.1" baseProfile="full" xmlns="http://www.w3.org/2000/svg" 
   height="400" width="400">
      <rect width="100%" height="100%" fill="red"/>
</svg>
```

**Comment by atmgrifter00** [comment]
The issue we have with this, is that we have no control over the SVG our user will be attempting to load. In the version of SharpVectors we were using before, we at least would get a visual representing the percentage-sized object in the DrawingGroup, it was just given some arbitrary default size of 640x480.

At the point where we exercise the code I listed above, we have no knowledge of what the target area size is. Your suggestion actually works for the cases where the SVG contains only percentage-based size constraints. That is, if we just hard code the 640x480 size in the way you outlined, we get expected behavior. However, it becomes problematic for SVG that does not contain percentage-based size constraints, particularly when the desired bounds of the geometry are larger than the artificial constraints we would be imposing. As you might expect, the image gets clipped.

So, this SVG would be clipped when providing the 640x480 constraints in the way you suggest:
```
<svg version="1.1" baseProfile="full" xmlns="http://www.w3.org/2000/svg">
<circle cx="350" cy="350" r="350" fill="green"/>
</svg>
```

Note that SVG with a smaller desired size than the artificial constraints imposed actually comes back with the desired bounds (not the artificially larger bounds).

In my mind, there are two changes in behavior that would be ideal to me (from my selfish use case perspective). The first, is, when dealing with SVG that only has percentage-based sizing constraints, and no artificial size constraints have been imposed through the SharpVectors API (your suggestions), that we still get a WPF drawing representing that/those SVG object(s) but they are given some arbitrary bounds (640x480, or whatever). This is very debatable behavior, but that's what would work for us.

The second suggestion might be less controversial (but possibly a pain to implement...and could have performance implications), where if there is a mix of percentage-based size objects, and pixel-sized objects, the bounds of the percentage-based sized objects is ultimately determined by the union of the pixel-based sized objects.

I totally understand if you don't agree with those behaviors, they are just what we might need to get the ideal behaviors we're looking for. Without them (or some other workaround to achieve the same behavior), I don't think we can move on to the new version you just made and we have to stick with the older one we've forked and are maintaining.

**Comment by atmgrifter00** [comment]
Sorry, I totally glossed over this comment from you:

> the WPF implementation is WpfSvgWindow, defined a default dimension to prevent such issues, but it was giving problems to others so it was removed.

I'm going to talk with folks on my end to determine what we consider to be necessary SVG we have to support. It's possible that the use cases that aren't working for us are ultimately pathological.
