### ISSUE TITLE
Will this project support uwp in the future？

### ISSUE THREAD

**Issue by BigHeadDev** [ElinamLLC/SharpVectors#120]
On Windows 10 universal platform, although image control already supports SVG direct binding, for SVG with transparent background, there will be pure black background problem. I hope to see SharpVectors in uwp platform

**Comment by paulushub** [comment]
Thanks for the question. Yes, the plan for SharpVectors is multi-platform supports from the very beginning.
For UWP, there was an initial disappointment with lack of radial-gradient support but the main problem is laziness! I am still too comfortable with my Windows 7 machines, only boot Windows 10 machines to update them.
WinUI 2.x-3 is looking cool and I will soon upgrade my current workstation to Windows 10 and hopefully kill the laziness. By the end of January 2020, we should have some support for UWP.
The current UWP's SVG support, through the SvgImageSource, is minimalist implementation for icons.
