### ISSUE TITLE
Removed original author attribution?

### ISSUE THREAD

**Issue by RickBullotta** [ElinamLLC/SharpVectors#121]
I'm curious why you removed attribution to the original authors of some of these modules. As one of the early developers on SharpVectors I was surprised to see it all stripped.  That generally considered kind of uncool.

**Comment by paulushub** [comment]
I have provided a credit section on this project home page. If by attribution you mean comments like the following in some of the files
```xml
/// <developer>niklas@protocol7.com</developer>
/// <completed>80</completed>
```
I removed what I considered non-standard Xml comments as part of the cleanup and documentation improvements efforts, an on-going process to improve .NET 1.1 codes.
I could add these to the project home page if that will satisfy your requirements for attribution.
