### ISSUE TITLE
WPF .NET Core 3

### ISSUE THREAD

**Issue by Lorymi** [ElinamLLC/SharpVectors#122]
Hi. Please support for .NET Core 3 for WPF applications

**Comment by paulushub** [comment]
Pending Task: #100 
This fork by @eddiemon is doing just that now: https://github.com/eddiemon/SharpVectors

**Comment by paulushub** [comment]
@Lorymi Need some inputs; which .NET Core to support? Core 3, Core 3.1 or both?

**Comment by schmitch** [comment]
well I think if you support 3.0 you also support 3.1, but I think you can start with 3.1 since not a lot of people will use 3.0 since 3.1 is an lts and already released.

(just saying as an outsider)

**Comment by paulushub** [comment]
@schmitch Thanks for that quick feedback. Working on it now.
For NetFramework: 4.0, 4.5, 4.6, 4.7, 4.8 nuget packages will be available.
For NetStandard: 2.0 {and 2.1} (currently, it seems 2.0 is more widely supported)
For NetCore:? Still resolving....

**Comment by schmitch** [comment]
well the library only supports wpf so .net standard is enough.
.net standard means, it is usable from dotnet core 3.0 and everything beyond (which is the **first** version that supports wpf)

**Comment by paulushub** [comment]
The multi-targets release is now active.
