### ISSUE TITLE
Exception occurs using WPF controls if a dynamic assembly exists 

### ISSUE THREAD

**Issue by DaveInCaz** [ElinamLLC/SharpVectors#125]
`SvgImageBase.GetEntryAssembly() `contains two similar clauses like the following:

```
                    asm = (
                          from assembly in AppDomain.CurrentDomain.GetAssemblies()
                          let assmName = Path.GetFileName(assembly.CodeBase).Trim()
                          where assmName.EndsWith(".exe", comparer)
                          where !string.Equals(assmName, "XDesProc.exe", comparer) // should not be XDesProc.exe
                          select assembly
                          ).FirstOrDefault();
```

It is iterating through all the loaded assemblies that are loaded. 

_But the `CodeBase `property will throw an exception if called on an assembly which is dynamic._ My understanding is that dynamic in this sense means it was created at runtime by reflection, or something along those lines. This article helped with some explanation: https://stackoverflow.com/a/2614993/3195477

However it is pretty easy to filter these dynamic assemblies out by added a `where `clause:

```
                    asm = (
                          from assembly in AppDomain.CurrentDomain.GetAssemblies()
       ***                where !assembly.IsDynamic
                          let assmName = Path.GetFileName(assembly.CodeBase).Trim()
                          where assmName.EndsWith(".exe", comparer)
                          where !string.Equals(assmName, "XDesProc.exe", comparer) // should not be XDesProc.exe
                          select assembly
                          ).FirstOrDefault();
```

As far as I can tell this would not break the logic here because the `XDesProc` assembly is not going to be dynamic anyway.

This seems necessary to avoid the exception.

----

Note -- In my specific case, I am using https://github.com/force-net/DeepCloner in my project, and apparently it creates a dynamic assembly. This was not something I was even really aware of, so initially the exception which arose from `CodeBase `throwing was extremely confusing & hard to debug.

---

Also I found it a little odd that this same code block was repeated in the catch. I wonder if suppressing failure would actually be better in this instance; I'm not sure but having a catch block throw a new exception doesn't seem intentional. I don't know enough about this assembly loading code to know if there are other potential points of failure. There is a trace log in there already which might suffice.

**Comment by paulushub** [comment]
@DaveInCaz These are attempts to detect the designer application, which will normally use temporal compiled version of the assemblies, and cannot be a source of SVG resource files (the user application will).
Unfortunately, unlike Windows Forms, WPF does not define the designer interfaces, so the behavior is application specific: say (Visual Studio and Blend for Visual Studio).

**Comment by DaveInCaz** [comment]
But what would be the harm in adding 

where !assembly.IsDynamic

?

As it is now, it makes a big assumption that the entire application won't have any dynamic assemblies.

**Comment by paulushub** [comment]
@DaveInCaz I think looking for Exe in design mode should have nothing to do with dynamic. This code should not run except in a designer, that is the issue I am looking into or I do not yet understand the issue?

**Comment by DaveInCaz** [comment]
@paulushub  I think I understand what you mean now. Right, if it only ran in the designer then I think it would not be an issue.

**Comment by paulushub** [comment]
@DaveInCaz I will simply filter out the dynamic and catch exception in the `GetAppName()` method.
This method is called in the base constructor and should never throw an exception, since the whole point is an attempt to get initial value for `_appName` and here is no test for designer mode.

Which version of the SharpVectors are you using?

**Comment by DaveInCaz** [comment]
@paulushub thanks for looking into this. 

I'm using 1.5.0.

**Comment by paulushub** [comment]
@DaveInCaz If possible, see if the current commits works for you. Planning for a release on Monday.

**Comment by DaveInCaz** [comment]
I gave it a shot but unfortunately we're stuck on Visual Studio 2015 here and so I can no longer compile the projects. Is there any kind of binary distribution?

**Comment by paulushub** [comment]
@DaveInCaz Sorry, I have committed the output folder now.

**Comment by DaveInCaz** [comment]
@paulushub thanks, I downloaded and tried out the DLLs. 

I get a different problem now. Though, maybe it is not important (?) 

When I run & load the WPF `Window` which uses SV,  in the output window it shows this:

```
VB6.EXE Error: 0 : System.NullReferenceException: Object reference not set to an instance of an object.
   at SharpVectors.Converters.SvgImageBase.GetEntryAssembly()
VB6.EXE Error: 0 : System.NullReferenceException: Object reference not set to an instance of an object.
   at SharpVectors.Converters.SvgImageBase.GetEntryAssembly()

(...repeats...)
```

Note that `VB6.exe` is the main unmanaged process.

Despite this message however, the application seems to function OK. It also is working fine in the XAML designer, where previously I was getting some errors.

**Comment by paulushub** [comment]
@DaveInCaz Thanks for the feedback, that exception should be fixed. For debugging purpose, some exceptions are logged and that is what is showing in the output window.
I have updated the outputs, still trying to find the best way to handle the `pdb vs snupkg` options - sorry!

**Comment by DaveInCaz** [comment]
BTW so far I have been using this locally (not the Nuget package) and I believe it solves the issue in the designer. When 1.6 is released I'll certainly update to that version and hopefully at that point its behind us :)  

I don't know if this issue needs to be left open until 1.6 or not..?

**Comment by paulushub** [comment]
Sorry, for the delay. I will give it a shot this weekend and get something out by Monday.

**Comment by DaveInCaz** [comment]
Hi @paulushub - thank you so much for your help & work on this whole project.

**Comment by paulushub** [comment]
The multi-targets release 1.6 is now active.
