### ISSUE TITLE
SVG not showing at design time

### ISSUE THREAD

**Issue by Inzta** [ElinamLLC/SharpVectors#126]
I have started using SharpVectors v1.5 to show my SVG files in WPF.

I have a CommonStyles project which contains all my SVG files in an icons folder and is referenced in my mainApp project.

I do the following:
```c#
<Image Source="{svgc:SvgImage Source=/CommonStyles;/icons/WarningIcon.svg}" Height="40" Width="40"></Image>
```

This shows up fine at run time, but at design time my WarningIcon is not shown.
So I tried this instead:
```c#
<Image Source="{svgc:SvgImage Source=/icons/WarningIcon.svg, AppName=CommonStyles}" Height="40" Width="40"></Image>
```
But this neither works at design time nor at run time. If going back to SharpVectors v1.4 the last line works fine at design time, but never shows at run time. 
I have set the build action on my SVG to Resource.

Running .NET Framework 4.7.2 in Visual Studio 2019
What is the way to go here?

**Comment by paulushub** [comment]
@Inzta This is an issue I am looking into and explains why the issue #89 is still not closed. Hopefully, the next update will provide a way out. The `AppName` does not work in this case.
If you have the `CommonStyles` project as part of the solution, it might not be built; Visual Studio might create a temporal build to let the designer work but the WPF Designer does not provide any design-time interface for controls to implement.

With the `AppName`, SharpVectors tries to create the [pack url](https://docs.microsoft.com/en-us/dotnet/framework/wpf/app-development/pack-uris-in-wpf) and use it to resolve the location of the file.

**Comment by DavidNgoDev** [comment]
I have a similar issue.  When working with .NET Framework 4.7.2 or .NET Framework 4.8, everything is fine for me. The SVG shows up at design and run time. However when moving to .NET Core 3.1. The SVG no longer shows up at design time but shows up at run time. I'm using version 1.6 and used the following control
`<svgc:SvgViewbox Source="/assets/image.svg" Height="30" />`

**Comment by tormodfj** [comment]
Curiously, the _binding converter_ mechanism seems to work pretty reliably in design mode:
```xml
<Image Source="{Binding Converter={svgc:SvgImageConverter AppName=MyApp}, ConverterParameter=/Resources/sample.svg}"/>
```

Consequently, if I create a class like this:
```csharp
public class SvgImage : Image
{
    public string SvgSource
    {
        get => (string)GetValue(SvgSourceProperty);
        set => SetValue(SvgSourceProperty, value);
    }

    public static readonly DependencyProperty SvgSourceProperty = DependencyProperty
        .Register("SvgSource", typeof(string), typeof(SvgImage), new PropertyMetadata(string.Empty, OnSvgSourceChanged));

    private static void OnSvgSourceChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is SvgImage image)
        {
            var converter = new SvgImageConverterExtension
            {
                AppName = "MyApp"
            };
            var binding = new Binding
            {
                Converter = converter,
                ConverterParameter = e.NewValue
            };

            image.SetBinding(SourceProperty, binding);
        }
    }
}
```
... then I can use this in my XAML and my SVG icons will be displayed at design time:
```xml
<my:SvgImage SvgSource="/Resources/sample.svg" />
```

**Comment by paulushub** [comment]
@tormodfj The use case is that the SVG icon files are not directly included in the application resources but are in a different DLL.

**Comment by tormodfj** [comment]
My apologies! I experienced issues with `{svgc:SvgImage ...}` not working at all at design time, regardless of where the icon files resided. I suspected there was a common underlying issue, and wanted to share a workaround. Sorry if I caused any confusion.

**Comment by paulushub** [comment]
@tormodfj Sorry, I thought you did not understand the issue. I did not understand your post.

**Comment by paulushub** [comment]
We have finally resolved this issue with the current update to the repository.
