### ISSUE TITLE
arrows rendered incorrectly

### ISSUE THREAD

**Issue by SyKaLus** [ElinamLLC/SharpVectors#127]
arrows drawn with inkscape are rendered incorrectly by SharpVectors, see attached png files.

This is how edge and firefox display my arrow (pretty much the same as inkscape's idea)
![arrow_edge](https://user-images.githubusercontent.com/61713725/75759956-b2f15900-5d36-11ea-91cc-3d707df81e06.png)
![arrow_firefox](https://user-images.githubusercontent.com/61713725/75759959-b389ef80-5d36-11ea-9d70-df83731be084.png)

Here is how SharpVectors renders it:
![arrow_SharpVectors](https://user-images.githubusercontent.com/61713725/75759960-b4228600-5d36-11ea-9b55-90d05c0f0481.png)

Here's the svg source:
[arrow.svg.txt](https://github.com/ElinamLLC/SharpVectors/files/4280253/arrow.svg.txt)

A fix would be very much appreciated

**Comment by paulushub** [comment]
@SyKaLus Sorry for the delay, this issue is now fixed in the latest commit.
