### ISSUE TITLE
Support for css custom properties/variables?

### ISSUE THREAD

**Issue by jhndnnqsc** [ElinamLLC/SharpVectors#128]
svgsupports the css custom property syntax. 

```
<html>
  <style>

  :root
  {
    --myfill: orange;
    --othefill: purple;

  }

  </style>
  <svg width="250" height="250" viewBox="0 0 250 250">
    <rect fill="var(--myfill,pink)" x="0" y="0" width="150" height="120"/>
  </svg>
</html>
```
This code will use the --myfill color, if defined, otherwise it will use pink. What I'd like to do is have a fixed, unmodified svg and pass in different values for the given variables to change things at runtime. I looked through the source code and didn't see anything obvious but does SharpVectors support this? If not, what would be the right area to investigate adding this feature?

**Comment by paulushub** [comment]
@jhndnnqsc Thanks for the information. Custom properties or CSS variables are not supported. 
First the above will not be rendered, since it is not a valid SVG, so lets start with something like
```xml
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" 
        xmlns:xlink="http://www.w3.org/1999/xlink" 
	width="250" height="250" viewBox="0 0 250 250">
  <style>
  :root
  {
    --myfill: orange;
    --othefill: purple;

  }
  </style>
  <g>
    <rect fill="var(--myfill,pink)" x="0" y="0" width="150" height="120"/>
  </g>
</svg>
```
CSS styling support is implemented in the `SharpVectors.Css` project, and I will have to read the CSS specification to see the best way to classify the `var() function`. 

[CSS Custom Properties for Cascading Variables Module Level 1](https://drafts.csswg.org/css-variables/#defining-variables)
[MDN Web Docs: Custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/--*)
[MDN Web Docs: Using CSS custom properties (variables)](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties)

* If considered as a styling block, it will be parsed in the `CssStyleDeclaration` class.
* If considered as a rule, a custom rule will be defined extending `CssRule` class.
* If considered a value, a custom value will be defined extending `CssValue` class.
* etc

Now for the above style, the contents of the `:root` will be parsed and stored in `CssStyleDeclaration` class instance, so we will only need to correctly parse and process the `var() function`.

If you can give it a shot, it will be a great help since I am currently working on other tasks.

**Comment by jhndnnqsc** [comment]
@paulushub thanks for the response. I think what you are describing would be supporting -- variables in the embedded style of the SVG file. While a useful feature, it's not exactly my use case. Ideally, I would have an unstyled SVG like this
```
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" 
        xmlns:xlink="http://www.w3.org/1999/xlink" 
	width="250" height="250" viewBox="0 0 250 250">
  <g>
    <rect fill="var(--myfill,pink)" x="0" y="0" width="150" height="120"/>
  </g>
</svg>
```
And then to use, it would look something like
```
var vars = new Dictionary<string, string>
{
  { "--myfill", "pink"},
  { "--otherfill", "orange" }
};
MemoryStream dummy = new MemoryStream();

var converter = new Stream
SvgConverter(true, false, new WpfDrawingSettings() { EnsureViewboxSize = true });

// ?? maybe this?
converter.CssVariables = vars;
converter.Convert(stream, dummy);
return new DrawingBrush(converter.Drawing);
```
The goal is to have a single SVG file that can be used unmodified but styled differently for different use cases. In this use case there isn't a need for the CSS to understand --var - the code that is parsing the SVG fill attribute ( along with other attributes ) needs to look up the variables. Looking through the code it seems like this would probably go in `SvgStyleableElement.GetPresentationAttribute` - the code would just need to identify the property string matches the var() pattern and then lookup the variable by name and use that for the actual string value.

I understand this may be a little esoteric and specific to my needs so there might not be interest in including such a feature in the main software. My backup plan is to dynamically modify the svg in memory to push in the variable content directly as embedded css styles before parsing.

**Comment by paulushub** [comment]
@jhndnnqsc I think you really do not need the CSS custom properties to achieve that. The library supports user-defined styles; `WpfDrawingSettings.UserCssFilePath` and 'WpfDrawingSettings.UserAgentCssFilePath`. So using CSS classes and IDs, you might get that working easily.
I was trying to build samples with that to demonstrate themes support in applications, Also, looking at the possibility of using WPF inherit dependency properties to implement.
That way, the styling can be dynamically modified and the system updates accordingly.

**Comment by jhndnnqsc** [comment]
@paulushub unfortunately I don't think the css file path approach would work. My application is more like a drawing program where users can import SVG and CSS files and everything is stored in memory. In my application there are UI elements defined by the user which can be styled via CSS via type and class selectors. The SVG files are icons that can then be applied to the UI elements and need to get their style passed into them. The variable method would be pretty clean since the user could define global and class specific variables that would be passed into the SVG renderer. It might be possible to use styles to do the same but I'd have to think about this a little bit. An even bigger complication is that the end result needs to work in WPF as well as QT, iOS and HTML5 apps so using any WPF features wouldn't be helpful.

**Comment by paulushub** [comment]
@jhndnnqsc Interesting project. I get it, lets support the `var() function`. Please if you have a little time, can you investigate a regular expression for passing the `var() function`? I will take it from there.

**Comment by jhndnnqsc** [comment]
@paulushub sounds good. I'm not a regex superstar but here's some example code which extracts what's needed. The pattern is basically `var(--{var_name} {, optional fallback})` where if the var_name exists in the variable map that string should be used, otherwise the fallback is used if it was specified. Let me know if this doesn't work or if you need something in a different form

```
using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace ConsoleApp1
{
  class Program
  {
    static Dictionary<string, string> vars = new Dictionary<string, string>
    {
      { "foo", "orange" },
      { "foo2", "pink" }
    };

    static string GetAttributeValue(string str)
    {
      // valid variables must start with -- and must be a valid css indentifier
      // this regex doesn't deal with escape characters
      Regex regex = new Regex(@"var\(\s*--([_a-zA-Z][_a-zA-Z0-9\-]+)(:?,\s*(.+?)\s*)?\)");

      var match = regex.Match(str);
      if (match.Groups[0].Success)
      {
        var varName = match.Groups.Count > 0 ? match.Groups[1].ToString() : "";
        if (vars.ContainsKey(varName)) return vars[varName];
        else
        {
          // fallback 
          return match.Groups.Count > 2 ? match.Groups[3].ToString() : "";
        }
      }
      return str;
    }

    static void Test(string str)
    {
      Console.WriteLine($"'{str}' --> '{GetAttributeValue(str)}'");
    }
    static void Main(string[] args)
    {
      Test("red");  
      Test("var(--foo)"); 
      Test("var( --foo2)"); 
      Test("var( --foo3)"); 
      Test("var(--foo"); 
      Test("var(--foo,red)"); 
      Test("var(--foo3, red)"); 
      Test("var(--foo3, red, green)"); 
      Test("var(--foo red  green)"); 
      Console.ReadKey();
    }
  }
}
```
outputs
```
'red' --> 'red'
'var(--foo)' --> 'orange'
'var( --foo2)' --> 'pink'
'var( --foo3)' --> ''
'var(--foo' --> 'var(--foo'
'var(--foo,red)' --> 'orange'
'var(--foo3, red)' --> 'red'
'var(--foo3, red, green)' --> 'red, green'
'var(--foo red  green)' --> 'var(--foo red  green)'
```

**Comment by paulushub** [comment]
@jhndnnqsc I made initial commit of codes to support the CSS custom properties. For now the support is only for colors or brushes.
The value of custom properties such as `--myfill` will be extracted from a `WpfDrawingSettings.CssVariables` dictionary object or from the styles as in the sample or fallback.
`WpfDrawingSettings.CssVariables` is always defined (will not be null), so you simply modify it or replace it.

**Comment by jhndnnqsc** [comment]
@paulushub works great in my somewhat limited testing! Thanks for adding this so quickly - I hope some other people find it useful as well.

**Comment by paulushub** [comment]
@jhndnnqsc Thanks for the verification. Most do not create SVG files in their projects, those who do might find this useful. I never knew about CSS variables until you mentioned it, for instance.
Some projects currently modifying the generated output drawing might also find this useful.
Lets keep this thread open for now to see how far we can build on it as others put in their requests.
