### ISSUE TITLE
Flags rendered incorrectly

### ISSUE THREAD

**Issue by andrefmartins99** [ElinamLLC/SharpVectors#129]
Hello so I´ve found that some flags are being rendered incorrectly. Those flags are from Cabo Verde, Iran, Republic of Kosovo, Niue, South Africa, South Korea, Tajikistan, Uzbekistan e Solomon Islands. There could be more but these are the ones I found. Please find attached an example of the flag of Cabo Verde being shown in Chrome and after its rendered. Sorry for the bad quality photos.
![chrome](https://user-images.githubusercontent.com/58475232/80851875-3b4b8780-8c1c-11ea-9485-1ec29321dc2b.jpeg)
![wpf](https://user-images.githubusercontent.com/58475232/80851879-3f77a500-8c1c-11ea-9853-6f259f2b4253.jpeg)

Thank you for your time.

**Comment by paulushub** [comment]
@andrefmartins99 Thanks for the post. Where do I find the SVG files for the flags for testing?

**Comment by paulushub** [comment]
@andrefmartins99  Using the SVG flag file from Wikipedia, I could reproduce this bug. I will investigate now and fix it soon.

**Comment by paulushub** [comment]
@andrefmartins99 I have fixed the issues reported here with today's commit. There was no issue with the South Africa and the Kosovo flags.
Please verify these and give some feedbacks.

**Comment by andrefmartins99** [comment]
Everything is working fine right now ty
