### ISSUE TITLE
Is it possible to include SVGs in a resource dictionary as ImageSource objects?

### ISSUE THREAD

**Issue by DaveInCaz** [ElinamLLC/SharpVectors#130]
There are certain SVGs which get used in several places in my app so I thought to consolidate them to resources. However there doesn't seem to be a way to declare an `ImageSource `object directly in XAML at all.

What I am doing for now as a workaround is making static objects in C# and then using `x:Static` to reference them in XAML. Example:

```
    static public class ImageSources
    {
        static public ImageSource SomeIcon = CreateSvgImageSource("path\to\icon\file.svg");

        ....

        static private ImageSource CreateSvgImageSource(string file) =>
            new SvgImageExtension(file).ProvideValue(null) as ImageSource;
    }
```

So this makes use of the `SvgImageExtension` but in a somewhat unconventional way.

Is there a better way to do this either in XAML itself or as an improvement of this C# approach? Thanks

**Comment by paulushub** [comment]
Not tested, You can put `SvgImage` in the Resources section of the Window/Application or a separate resource file and use it as a regular resource:
```xml
<svgc:SvgImage Source="/Resources/path/to/icon/file.svg" x:Key="SomeIcon"/>
```

**Comment by DaveInCaz** [comment]
Thanks, that does seem to work. I'm able to use the image by key in a Window Icon and also Image Source, both in XAML.
