### ISSUE TITLE
Source changing not working with images of the same size?

### ISSUE THREAD

**Issue by nocluk** [ElinamLLC/SharpVectors#131]
We have one SvgControl and based on the selection performed by the user different SVG files should be shown.

For this we bound the Source property of the SvgControl, but the new SVG won't be shown. Also calling the "Load(uriSource, useAsync)" function in the code behind does not cause the image to change.

We observed that this occurs when the image size of the old and the new file is the same.
Resizing the SvgControl will cause the new image to be loaded.

The atachements contain a small sample project that shows the observed issue.

[SVGTest.zip](https://github.com/ElinamLLC/SharpVectors/files/4597620/SVGTest.zip)

**Comment by paulushub** [comment]
@nocluk `SvgControl` is a work in progress so please do not use it, that is why it is not documented and there is no sample code using it. 
You can use the `SvgCamvas` and `SvgViewbox`. See the demo samples in the `TutorialSamples` directory for how to use these controls.

**Comment by nocluk** [comment]
Thank you for the fast responce.

Changing the used Control to SvgCanvas resolved the observed issue.

The reason why we firstly choose SvgControl was the SizeMode property, but we are able to handle it with surounding controls.

**Comment by paulushub** [comment]
@nocluk Thanks for the update. `SvgControl` is meant to do a lot more on its own, including interactivity. For that it will require the completion of the scripting support, which is still work in progress so for now I kept it that way and never announced it.
