### ISSUE TITLE
Invalid index is used for _height in SvgSizeF structure

### ISSUE THREAD

**Issue by MikeGratsas** [ElinamLLC/SharpVectors#133]
Update Source/SharpVectorCore/Svg/SvgSizeF.cs implementation:

public override int GetHashCode()
{
    double[] values = this.GetHashValues();
    return values[0].GetHashCode() ^ values[1].GetHashCode();
}

**Comment by paulushub** [comment]
@MikeGratsas Thanks for spotting and reporting this issue.

**Comment by MikeGratsas** [comment]
You can use SonarQube to analyze code and find possible issues

**Comment by paulushub** [comment]
@MikeGratsas Thank you, looking into it.
