### ISSUE TITLE
fontFamily local variable is used twise instead of fontEncoding in SvgDocument class

### ISSUE THREAD

**Issue by MikeGratsas** [ElinamLLC/SharpVectors#134]
Modify Source/SharpVectorModel/DocumentStructure/SvgDocument.cs GetFontUrl method implementation:

                    string fontFamily = fontRule.FontFamily;
                    string fontEncoding = fontRule.EmbeddedEncoding;
                    string fontMimeType = fontRule.EmbeddedMimeType;
                    if (!string.IsNullOrWhiteSpace(fontFamily) 
                        && !string.IsNullOrWhiteSpace(fontEncoding)
                        && !string.IsNullOrWhiteSpace(fontMimeType)
                        && !fontMimeType.Equals("base64", StringComparison.OrdinalIgnoreCase))
                    {

**Comment by paulushub** [comment]
Thanks for spotting this, it seems `fontEncoding` is not needed too.
