### ISSUE TITLE
SvgCanvas Background Question

### ISSUE THREAD

**Issue by Arukaito** [ElinamLLC/SharpVectors#137]
Hello, this is my first time working with WPF 
So im fairly new to the concept of Canvas, SvgCanvas etc. 

I've got my project running and it works but i want to invert the colors of the SVG, so far i have inverted the colors using INKSCAPE and exporting from inskcape using Optimized SVG

But the SVG Canvas is white and my inverted colors are white too so i just cant see anything

Is there a way to change the background color of the SVGCanvas to Black ?
Or is there a way to invert the colors of the SVG using SharpVectors so i dont have to use Inkscape?

**Comment by paulushub** [comment]
@Arukaito Several ways to achieve that, but please show a simple picture of what the result will look like.

**Comment by Arukaito** [comment]
Ok so the first thing i would need to achieve (  with some help ) is to put the background as Black instead of White, If i recall correctly SVGs are rendered data so the background color can be controlled 

The second thing that i think it would be harder is to change the colors of the Text, Boxes and Lines manipulating de SVG data via code. i dont know if we can do that with Sharpvectors

want an option to just put the background black or invert all the colors of the SVG because the imported SVG will not always be the same 

Attached a test SVG and final look image

[SVGLooks.zip](https://github.com/ElinamLLC/SharpVectors/files/4814542/SVGLooks.zip)

**Comment by paulushub** [comment]
@Arukaito Thanks for the update. Sorry, only the `ImageSvgConverter` currently implements that feature. This is test with your sample.
**NOTE**: The text "TESTING" color is black and will not show in this result.
```csharp
private void Test()
{
    // 1. Create conversion options
    WpfDrawingSettings settings = new WpfDrawingSettings();

    // 2. Select a file to be converted
    string svgTestFile = @"..\..\SVGLooks\testing.svg";

    // 3. Create a file converter
    ImageSvgConverter converter = new ImageSvgConverter(settings);
    converter.Background = new SolidColorBrush(Colors.Black);

    // 4. Perform the conversion to image  
    converter.EncoderType = ImageEncoderType.PngBitmap;
    converter.Convert(svgTestFile);
}
```
![testing](https://user-images.githubusercontent.com/809351/85320186-a53a2c00-b4fd-11ea-86fd-71234e02431a.png)

Immediately, what you can do is override the `SvgCanvas.CreateDrawing()` and add a background layer to the output.
```csharp
protected override DrawingGroup CreateDrawing()
{
      var currentDrawing = base.CreateDrawing();
      var bounds = currentDrawing.Bounds;
      var backgroundLayer = new DrawingGroup();
      var backgroundDrawing = new GeometryDrawing(new SolidColorBrush(Colors.Black), null, new RectangleGeometry(bounds);
      backgroundLayer .Children.Add(backgroundDrawing);

      var combinedDrawing = new DrawingGroup();
      combinedDrawing .Children.Add(backgroundLayer);
      combinedDrawing .Children.Add(currentDrawing);
      
      return combinedDrawing;     
}
```
Another way is, if you have control over all the SVG files, then add layer to them in the InkSpace and style them through custom CSS properties as illustrated in this thread: https://github.com/ElinamLLC/SharpVectors/issues/128

I will look into extending this feature to the controls and other converters.

**Comment by paulushub** [comment]
@Arukaito I have created a sample from the above codes and also color the `TESTING` text element.

[WpfApp2.zip](https://github.com/ElinamLLC/SharpVectors/files/4825495/WpfApp2.zip)
