### ISSUE TITLE
Rendering pattern tag incorrect

### ISSUE THREAD

**Issue by jianghaoyuan2007** [ElinamLLC/SharpVectors#140]
I used the library to render a svg file, it was not expected as Google Chrome.

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg viewBox="0 0 230 100" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <pattern id="star" viewBox="0,0,10,10" width="10%" height="10%">
      <polygon points="0,0 2,5 0,10 5,8 10,10 8,5 10,0 5,2"/>
    </pattern>
  </defs>

  <circle cx="50"  cy="50" r="50" fill="url(#star)" stroke="#FF0000" stroke-width="1"/>
  <circle cx="180" cy="50" r="40" fill="none" stroke-width="20" stroke="url(#star)"/>
</svg>

**Comment by jianghaoyuan2007** [comment]
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg viewBox="0 0 230 100" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <pattern id="star" viewBox="0,0,10,10" width="10%" height="10%">
      <polygon points="0,0 2,5 0,10 5,8 10,10 8,5 10,0 5,2"/>
    </pattern>
  </defs>

  <circle cx="50"  cy="50" r="50" fill="url(#star)" stroke="#FF0000" stroke-width="1"/>
  <circle cx="180" cy="50" r="40" fill="none" stroke-width="20" stroke="url(#star)"/>
</svg>

**Comment by jianghaoyuan2007** [comment]
`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg viewBox="0 0 230 100" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <pattern id="star" viewBox="0,0,10,10" width="10%" height="10%">
      <polygon points="0,0 2,5 0,10 5,8 10,10 8,5 10,0 5,2"/>
    </pattern>
  </defs>

  <circle cx="50"  cy="50" r="50" fill="url(#star)" stroke="#FF0000" stroke-width="1"/>
  <circle cx="180" cy="50" r="40" fill="none" stroke-width="20" stroke="url(#star)"/>
</svg>`

**Comment by jianghaoyuan2007** [comment]
![}QR3 1T%7R{7@LKI$4K@@JR](https://user-images.githubusercontent.com/2723353/87053128-2b5fad80-c234-11ea-9cda-377e24541073.jpg)

**Comment by jianghaoyuan2007** [comment]
![20200709223458](https://user-images.githubusercontent.com/2723353/87053454-8d201780-c234-11ea-83c9-767a8556d667.png)

**Comment by jianghaoyuan2007** [comment]
@paulushub What should I do? Can you help me ?

**Comment by jianghaoyuan2007** [comment]
https://www.w3.org/TR/SVG/images/pservers/pattern01.svg

**Comment by paulushub** [comment]
@jianghaoyuan2007 Thanks for reporting this issue. Looking into it.
Currently, `https://www.w3.org/TR/SVG/images/pservers/pattern01.svg` works correctly as shown below.
But the pattern defined on `https://developer.mozilla.org/en-US/docs/Web/SVG/Element/pattern` does not.

![pattern1](https://user-images.githubusercontent.com/809351/87219967-ca061e80-c39a-11ea-9b69-c821ce48884a.png)

**Comment by paulushub** [comment]
@jianghaoyuan2007 Sorry for the delay, I have finally fixed this issue with the latest commit. Please verify this, thank you.
