### ISSUE TITLE
Exception using a pack URI for SvgViewbox.Source ?

### ISSUE THREAD

**Issue by DaveInCaz** [ElinamLLC/SharpVectors#141]
I had a tag like this:
```
                            <svgc:SvgViewbox
                                Source="..\..\Foo\Images\Image123.svg"
                                />
```

Which I changed to this:

```
                            <svgc:SvgViewbox
                                Source="{x:Static View:ImageFiles.Image123}"
                                />
```

`View:ImageFiles.Image123` is a property whose `get` uses a function to provide pack URI syntax. 

However this resulted in an exception:

```
System.Windows.Markup.XamlParseException: ''Set property 'SharpVectors.Converters.SvgViewbox.Source' threw an exception.' 

...

From InnerException  (which is an ArgumentException):

...

pack://application:,,,/BarApp;component/Foo/View/Images/Image123.svg' is not a valid value for property 'Source'.
```

The actual URI is correct as far as I can tell.  Is there any reason `Source `won't accept a pack URI?

Thanks

**Comment by paulushub** [comment]
@DaveInCaz `System.Windows.Markup.XamlParseException` might mean syntax not right. Are you using resource file or local file path?
If resource, do you have this nested level of subfolders `/Foo/View/Images/`?

**Comment by DaveInCaz** [comment]
Hi @paulushub. Its an embedded resource.

I generate the pack URI using a function which is working elsewhere, so I don't think the path itself could be incorrect. Visually inspecting it, it looks fine. 

Here's an additional test I just did - I tried it 3 different ways.

```
                            <svgc:SvgViewbox
                                Source="..\..\Foo\Images\Image123.svg"
                                />

                            <svgc:SvgViewbox
                                Source="{x:Static View:ImageFiles.Image123}"
                                />

                            <Image
                                Source="{svgc:SvgImage Source={x:Static View:ImageFiles.Image123}}"
                                />
```

The first and third both work. The second does not.

Since #2 and #3 both are utilizing the identical source path, something must be different in how SvgViewbox is handling that path?

**Comment by paulushub** [comment]
> Its an embedded resource.

It seems you need to set the `Build Action` to `Resource` not `Embedded Resource`.

> Since #2 and #3 both are utilizing the identical source path, something must be different in how 
> SvgViewbox is handling that path?

1. Yes, it is different. `SvgImage` tries all sort of ways to find the file. Currently, `SvgViewbox` does only the standard approach.
2. `"..\..\Foo\Images\Image123.svg"` means the `SvgViewbox` is fetching it from the disk not as resource. Try copying the output to a different location and see if it will work.

**Comment by DaveInCaz** [comment]
@paulushub  I apologize, I said "Embedded Resource" which was incorrect - they are all set as "Resource" which I think is the norm for WPF.  I should have checked before posting that, I always forget which means which.

Regarding point #2 - while definitely I'd like to get to the bottom of this, perhaps standardizing that more extensive logic to use in both places would be a useful enhancement.

Also something else to consider is whether a missing source should in fact throw an exception or not. There's an argument to be made that this makes a bad situation worse when failure to show the image might only have been essentially cosmetic.

**Comment by paulushub** [comment]
> Regarding point #2 - while definitely I'd like to get to the bottom of this, perhaps standardizing that more extensive 
> logic to use in both places would be a useful enhancement.

There a plan for that, and will add support for external resource files.

> Also something else to consider is whether a missing source should in fact throw an exception or not. 

* In all cases, the exception is not thrown in design mode. 
* This issue was raised and for the `SvgImage` and `SvgImageConverter`, the exception throwing is disabled for these in both design and runtime. These are extension markup and are meant to be used in multiple places in a window, such as toolbars and list-views. The exceptions are logged using the Trace methods, and can be monitored if required.

For the controls (`SvgCanvas` and `SvgViewbox`), the exception is thrown still in runtime. I hope to add events to satisfy both sides of the arguments.

**Comment by DaveInCaz** [comment]
Personally I usually prefer strict exceptions because they help catch problems earlier. But many WPF controls do seem very permissive about bad inputs, although that seems to make debugging harder.

Thanks for your comments.
