### ISSUE TITLE
Similar Project SVGImage

### ISSUE THREAD

**Issue by jogibear9988** [ElinamLLC/SharpVectors#143]
Hello,

I've created a fork of a Codeproject Control a long time ago and created a Nuget and modified source a little.

https://github.com/dotnetprojects/SVGImage

I do not work on this much, only for Information

**Comment by paulushub** [comment]
I know about this project. I will add a link on the it.

**Comment by jogibear9988** [comment]
I've also included some animated SVGs as Example.
But also only simple animations work in it. The complex animation in horse.svg does not work

**Comment by paulushub** [comment]
Currently, SharpVectors implements the animation interfaces but are not yet rendered. So SVGImage is ahead in this feature.
You can add me as a contributor. Still have a lot to do with the SharpVectors, but can contribute the test samples and improvements as a lightweight renderer for WPF.
