### ISSUE TITLE
Bind SVG as string data to image

### ISSUE THREAD

**Issue by mcdikki** [ElinamLLC/SharpVectors#145]
Hi,

I have SVG data as string in a model and would like to bind the wpf Image or the SvgViewBox directly to this this string.
Is this possible?  
I managed to add a wrapper property to my model that creates a MemoryStream from the string data and bind it to the SvgViewBox.StreamSource property, but I'm not quite happy with this approach because I need to add view logic to the model.  

If this is not possible, may I suggest it?  
I could think of two ways to do it.  
* Add or extend the IValueConverter which is used to bind to the WPF <Image> control and allow to pass the svg data as string instead of the uri.
* Allow something similar to the html inline data approach for all the methods which takes an uri and embed the data like: `data:image/svg+xml;<svg>....</svg>`

Thanks a lot.

**Comment by paulushub** [comment]
No property is currently available for such feature, but the converters support method for handling `TextReader`, which can be a `StringReader`. I will look into it.

**Comment by mcdikki** [comment]
I'v tested a StringReader but got exceptions when I tried to bind it to the Source or StreamSource property in WPF.  
My main target is to use binding only my model in wpf without additional code behind.  

Is there a way to use the StringReader in such a manner?

Thanks for looking into it.

**Comment by paulushub** [comment]
`StringReader` is not a `Stream` and the properties currently available are for path (URI) and stream.

**Comment by paulushub** [comment]
This update add support for the embedded SVG contents as data source. See the `TutorialSamples/SvgCanvasSample and SvgViewboxSample` for demonstration.

**Comment by mcdikki** [comment]
This works great. Thank you very much.
