### ISSUE TITLE
ImageSharp Drawing backend

### ISSUE THREAD

**Issue by UkooLabs** [ElinamLLC/SharpVectors#150]
Would be nice to support image sharp's drawing lib (https://github.com/SixLabors/ImageSharp.Drawing) 

I had a look at starting myself but was not quite sure how to start so any advice would be appreciated.

**Comment by paulushub** [comment]
@UkooLabs How far is the SVGSharpie project?

**Comment by UkooLabs** [comment]
@paulushub 

It paused for a while due to winding rule issue, however that has since been fixed. But I find Sharp Vectors more complete and currently using it to rasterize svg's howver since its a website its not very pretty making gdi calls work and thus something like imagesharp would be great.

**Comment by paulushub** [comment]
@UkooLabs  I get it, let me improve the GDI+ renderer a bit more and see how to port that to the ImageSharp.Drawing for web sites. Lets keep this issue opened.

**Comment by paulushub** [comment]
@UkooLabs Sorry, I have decided to skip this support. 
I will support the new MAUI graphics, which will enable Skia and Direct2D, both are enabled for web environments.

**Comment by symbiogenesis** [comment]
> @UkooLabs Sorry, I have decided to skip this support. I will support the new MAUI graphics, which will enable Skia and Direct2D, both are enabled for web environments.

What is the best option for .NET MAUI at this time? Are there any repos or branches anywhere?

**Comment by paulushub** [comment]
The lack of Linux support in MAUI made is difficult to commit to, and with my work mainly now on AWS using Python/C++, MAUI is not even attractive for my hobbies - sorry!
