### ISSUE TITLE
svg viewbox containt

### ISSUE THREAD

**Issue by jsandv** [ElinamLLC/SharpVectors#151]
`
     <svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" 
      viewBox="0 0 1200 900">
`

Im loading an svg where **viewBox="0 0 1200 900"** is marked in the svg. These are the actual viewbox contstraints. When loading using something like:
```
       var svg = new SharpVectors.Converters.SvgCanvas();
       svg.Load(new Uri(picturePath));
```

These bounds are no where to be found. The viewBox dimensions from the svg file not supported?

**Comment by paulushub** [comment]
XAML is a vector format similar to the SVG, so we do not apply any restriction, so the displaying control or image object controls the size. 
If you wish to restrict the size to the viewbox, set the `WpfDrawingSettings.EnsureViewboxSize` property to true. This will simply add a transparent bounding box, with dimensions defined by the viewbox.

**Comment by jsandv** [comment]
I didnt find the option to provide the WpfDrawingSettings to SvgCanvas or SvgViewBox. Is this missing?

It looks like this works though:

`
	var settings = new WpfDrawingSettings
	{
		EnsureViewboxSize = true
	};
	FileSvgReader converter = new FileSvgReader(settings);
	DrawingGroup drawing = converter.Read(picturePath);
	if (drawing != null)
	{
		var svg = new Image();
		svg.Source = new DrawingImage(drawing);                   
	}

`

**Comment by paulushub** [comment]
@jsandv `SvgCanvas` and `SvgViewBox`  are extensions of standard WPF controls with defined behavior. They are based on `SvgDrawingCanvas` control, which is used in the sample applications with the `ZoomPanControl` to provide the scrolling and zooming.

[MSDN: Canvas](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.canvas?view=netcore-3.1) Defines an area within which you can explicitly position child elements by using coordinates that are relative to the Canvas area.
[MSDN: ViewBox](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.viewbox?view=netcore-3.1) Defines a content decorator that can stretch and scale a single child to fill the available space.

For most other cases, the `Image` will provide the functionality of a typical **Image View**. For a non-static or interactive image view, we hope to add `SvgControl` when the interactivity features are completed.

See the samples for `SvgCanvas` and similar samples for `SvgViewBox` in [TutorialSamples](https://github.com/ElinamLLC/SharpVectors/tree/master/TutorialSamples) to observe the differences.
