### ISSUE TITLE
DashCap is always set to "Flat", ignoring the stroke-linecap value

### ISSUE THREAD

**Issue by jhofinger** [ElinamLLC/SharpVectors#152]
If you convert the following SVG to XAML:

[linecap_test.zip](https://github.com/ElinamLLC/SharpVectors/files/5347349/linecap_test.zip)

(rendered with Inkscape)

![linecap](https://user-images.githubusercontent.com/12698538/95450520-b13fe180-0966-11eb-8c5e-d5caef4cb500.png)

all lines have DashCap=Flat set, so the rendering looks like this: 

![grafik](https://user-images.githubusercontent.com/12698538/95450795-1bf11d00-0967-11eb-9e87-b6627ab17717.png)

The specification doesn't mention this case explicitly (https://svgwg.org/svg2-draft/painting.html#LineCaps) and I'd personally say that the following sentence describes all impacts of this attribute, so your interpretation would be correct:

> stroke-linecap specifies the shape to be used at the end of open subpaths when they are stroked

However, all major browsers as well as Inkscape render the path identically with rounded / squared dash caps.

**Comment by paulushub** [comment]
Yes, it is always set to Flat in the code. I tried to remember why, but I still could not yet. I made the following note about it in WpfSvgPaint.cs.
```csharp
// This is the one that works well for the XAML, the default is not Flat as
// stated in the documentations...
pen.DashCap = PenLineCap.Flat;
```
For now, I have set it to match the Inkspace approach you described.

**Comment by paulushub** [comment]
@jhofinger The fix is committed. Please verify this, thank you.
