### ISSUE TITLE
When SVG is converted to image, the image is cut

### ISSUE THREAD

**Issue by qiu770** [ElinamLLC/SharpVectors#153]
Hi
when i use SvgImageExtension or FileSvgReader  convert to image, the image is cropped.

The resolution is 3000 * 2000
How to convert SVG to ImageSource completely without being cut

**Comment by paulushub** [comment]
@qiu770 Is the drawing cropped when you view it in any of the sample applications like the **WpfSvgTestBox**?

**Comment by paulushub** [comment]
@qiu770 Why do not close the issue without any comment? Is the issue resolved?
