### ISSUE TITLE
SVG file after conversion via SharpVectors the image is different

### ISSUE THREAD

**Issue by jbinko** [ElinamLLC/SharpVectors#154]
Attaching svg file in zip file. After conversion via SharpVectors the image has grey circle which is not in the original file.
See attached picture.
[10035-icon-service-App-Services.zip](https://github.com/ElinamLLC/SharpVectors/files/5398139/10035-icon-service-App-Services.zip)
![0](https://user-images.githubusercontent.com/1771881/96385038-7ffab900-1191-11eb-98bb-c3a9c09b9653.jpg)

**Comment by paulushub** [comment]
@jbinko Thanks for the information. Which version of the SharpVectors are you using? it seems to work on my PC.

![issue154](https://user-images.githubusercontent.com/809351/96386452-0afda280-11d6-11eb-86e1-e490dd223dc0.png)

**Comment by jbinko** [comment]
Thank you for response. I created sample app where it is reproducible. It is .NET Framework 4.8 SharpVectors Nuget Latest Stabe 1.0.0.
[SharpVectorsTest.zip](https://github.com/ElinamLLC/SharpVectors/files/5400858/SharpVectorsTest.zip)

**Comment by paulushub** [comment]
@jbinko Please move to [SharpVector.Reloaded](https://www.nuget.org/packages/SharpVectors.Reloaded/), which is currently at version 1.6.
Version 1.0 was created by one of the early users of SharpVectors in 2013, and with some reporting issues like this, I asked the publisher and *just* got the owner. I planned to update it with the next version 1.7 [Nuget Packages: Notes](https://github.com/ElinamLLC/SharpVectors/issues/147)

**Comment by jbinko** [comment]
Yes, I can confirm it fixed the issue. Thank you. Yes it would be nice to update SharpVector nuget package as it is default option for many users I guess. Thank you for great work you do!
