### ISSUE TITLE
SvgViewbox Source throws exception in 1.7.0

### ISSUE THREAD

**Issue by kotylo** [ElinamLLC/SharpVectors#161]
Hi,

I've downloaded the latest (1.7.0) version via Nuget. Straight up used the SvgViewbox:

    <svgc:SvgViewbox Source="/Icons/cctv.svg"/>

Via Designer, the Source is properly shown. Starting app, it crashes on InitializeComponent() with NullReferenceException of the `SvgViewbox.Source` (in View's constructor). Same with Sample Project in this repository. Workaround with `SvgImage` works, but I loose design time render.

Downgraded to 1.6.0. It works there.

**Comment by paulushub** [comment]
@kotylo Sorry, the fix is now active, Version 1.7.1.

**Comment by kotylo** [comment]
Thanks for a quick fix. Verified!
