### ISSUE TITLE
Change svg image colors at runtime?

### ISSUE THREAD

**Issue by SwaroopSomanna** [ElinamLLC/SharpVectors#163]
Alright, so I have a bunch of svg images that I've added to my application as resources. I'm using these images as a icons for several buttons by adding these images to svg viewport within the buttons. These images are multicolored and a part of it contains white color. Now what I want to achieve is during my application's runtime when I change the application theme (which I can handle) I want the white parts of the svg images in the buttons to become black. Is this possible with sharp vectors? If yes, how?

**Comment by paulushub** [comment]
@SwaroopSomanna I have looked into ways to support themes, but gave up! There is no standard way to handle it, so instead I provided several means to implement it.
For your case, is it just all white colors must become black or these are defined with style Id and/or class?

**Comment by SwaroopSomanna** [comment]
> For your case, is it just all white colors must become black or these are defined with style Id and/or class?
No style ID or classes is used. I just want  all white colors to become black. That's all.

**Comment by paulushub** [comment]
@SwaroopSomanna Sorry for the late response, please can you provide a sample SVG file for illustration?

**Comment by SwaroopSomanna** [comment]
> @SwaroopSomanna Sorry for the late response

That's ok

**Comment by SwaroopSomanna** [comment]
> @SwaroopSomanna please can you provide a sample SVG file for illustration?  

Now I'm using monochrome icons with blue foreground that works best for both black and white themes. Thanks anyway.
