### ISSUE TITLE
SvgViewbox is not taking into account viewbox (x, y, width, height) values during coordinate calculation

### ISSUE THREAD

**Issue by ohurskyi** [ElinamLLC/SharpVectors#165]
Hi @paulushub, thanks for amazing library.
Now we are integrating SharpVectors into one of our projects and during the testing I have observed strange issue using SvgViewbox.
Looks like drawings inside the viewbox is not taking into account viewbox (x, y, width, height) values during coordinate calculation, but take into account first drawing region.
Here you can find test project thats reproduced this issue.
[SharpVectorsTest.zip](https://github.com/ElinamLLC/SharpVectors/files/5637842/SharpVectorsTest.zip)

To breifly describe the issue with code:
```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" viewBox="-800 -800 1600.00 1600.00" >
  <g id="test-group">
    <!-- Note Strange behaviour without rect that define same region as viewbox will not work! -->
    <rect height="1600.00" width="1600.00" y="-800" x="-800" id="6137" style="fill:transparent;stroke:black;stroke-width=3;"/>
    <circle cx="0" cy="0" r="20" fill="turquoise" />
  </g>
</svg> 
```
Expected: small circle in the center of the svg.
Observed: circle stretched to fit the whole svg.

**Comment by paulushub** [comment]
@ohurskyi **SvgViewbox** is an extension of the WPF [Viewbox](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.viewbox?view=net-5.0).
You control the stretch behavior with the **Stretch** property.
> Expected: small circle in the center of the svg.

Set the `Stretch` to `None`!

**Comment by ohurskyi** [comment]
@paulushub Thank you for your response.
Yes if I will set `Stretch `property to `None `it will work, but I think it not the right way.
Let consider the next example:
 ```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" viewBox="-800 -800 1600.00 1600.00">
        <g id="test-group">
          <rect height="1600.00" y="-800.00" width="1600.00" x="-800.00" id="6137" style="background:transparent;stroke:none;opacity:0.0"/>
            <ellipse ry="772.00" rx="772.00" style="stroke-linejoin:miter;stroke-miterlimit:9;stroke:rgb(0,0,0);stroke-linecap:butt;fill:none;opacity:1" cx="0.00" id="6138" cy="0.00"/>
             <ellipse ry="692.00" rx="692.00" style="stroke-linejoin:miter;stroke-miterlimit:9;stroke:rgb(0,0,0);stroke-linecap:butt;fill:none;opacity:1" cx="0.00" id="6139" cy="0.00"/>
             <ellipse ry="612.00" rx="612.00" style="stroke-linejoin:miter;stroke-miterlimit:9;stroke:rgb(0,0,0);stroke-linecap:butt;fill:none;opacity:1" cx="0.00" id="6140" cy="0.00"/>
            <ellipse ry="562.00" rx="562.00" cx="0.00" id="6141" cy="0.00" style="fill:rgb(0,0,0);stroke:none;opacity:1"/>
        </g>
</svg>
```
Here we have a large viewbox rectangle with 1600 width and height. If I display it inside SvgViewbox  with `Stretch` set to `None` it will look like this, of course it will not fit inside the window (in my test window is Height="450" Width="800")  ![Viewbox_Stretch_None](https://user-images.githubusercontent.com/53793275/101160328-83f67380-3637-11eb-8bd9-73d9de983c6b.PNG) 

if `Stretch` is set to `Uniform` it's good ![Viewbox_Stretch_Uniform](https://user-images.githubusercontent.com/53793275/101160669-15fe7c00-3638-11eb-8888-7b5135f056ab.PNG)

Now if you copy the `SVG` above and place in any SVG online viewer (for example svgviewer.dev) and set the `width` and `height` of the `SVG`, the content will always fit into `SVG width and height` (if it 100px or 1000px), because `SVG` `width` and `height` define the `viewport` and `viewbox` define `user space` on which coordinate calculation is based.
I am trying to explain that `SVG` content rendering doesn't have a relation with `Stretch` property because the aspect ratio of an `SVG` image is defined by the `viewBox` attribute and for aligning used `preserveAspectRatio`.

To summarize, these two cases below will be displayed differently in `WPF` and `SVG viewer`:
1) WPF
```
<svgc:SvgViewbox Width="300" Height="300" Stretch="None">
  <svgc:SvgViewbox.SvgSource>
  <![CDATA[
  <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" viewBox="-800 -800 1600.00 1600.00">
    <g id="test-group">
      <rect height="1600.00" y="-800.00" width="1600.00" x="-800.00" id="6137" style="background:transparent;stroke:none;opacity:0.0"/>
      <ellipse ry="772.00" rx="772.00" style="stroke-linejoin:miter;stroke-miterlimit:9;stroke:rgb(0,0,0);stroke-linecap:butt;fill:none;opacity:1" cx="0.00" id="6138" cy="0.00"/>
      <ellipse ry="692.00" rx="692.00" style="stroke-linejoin:miter;stroke-miterlimit:9;stroke:rgb(0,0,0);stroke-linecap:butt;fill:none;opacity:1" cx="0.00" id="6139" cy="0.00"/>
      <ellipse ry="612.00" rx="612.00" style="stroke-linejoin:miter;stroke-miterlimit:9;stroke:rgb(0,0,0);stroke-linecap:butt;fill:none;opacity:1" cx="0.00" id="6140" cy="0.00"/>
      <ellipse ry="562.00" rx="562.00" cx="0.00" id="6141" cy="0.00" style="fill:rgb(0,0,0);stroke:none;opacity:1"/>
    </g>
  </svg>
  ]]>
  </svgc:SvgViewbox.SvgSource>
</svgc:SvgViewbox>
```
![Viewbox_Width_Height](https://user-images.githubusercontent.com/53793275/101164584-e488af00-363d-11eb-953b-44c60b58cbd0.PNG)

2) Online SVG viewer
```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="300" height="300" version="1.1" viewBox="-800 -800 1600.00 1600.00">
  <g id="test-group">
    <rect height="1600.00" y="-800.00" width="1600.00" x="-800.00" id="6137" style="background:transparent;stroke:none;opacity:0.0"/>
    <ellipse ry="772.00" rx="772.00" style="stroke-linejoin:miter;stroke-miterlimit:9;stroke:rgb(0,0,0);stroke-linecap:butt;fill:none;opacity:1" cx="0.00" id="6138" cy="0.00"/>
    <ellipse ry="692.00" rx="692.00" style="stroke-linejoin:miter;stroke-miterlimit:9;stroke:rgb(0,0,0);stroke-linecap:butt;fill:none;opacity:1" cx="0.00" id="6139" cy="0.00"/>
    <ellipse ry="612.00" rx="612.00" style="stroke-linejoin:miter;stroke-miterlimit:9;stroke:rgb(0,0,0);stroke-linecap:butt;fill:none;opacity:1" cx="0.00" id="6140" cy="0.00"/>
    <ellipse ry="562.00" rx="562.00" cx="0.00" id="6141" cy="0.00" style="fill:rgb(0,0,0);stroke:none;opacity:1"/>
  </g>
</svg>
```
![image](https://user-images.githubusercontent.com/53793275/101164648-05e99b00-363e-11eb-839c-43ef985143eb.png)

**Comment by paulushub** [comment]
> Yes if I will set Stretch property to None it will work, but I think it not the right way.

This is pure WPF question, not an issue with the control.

Try viewing the same SVG with the online viewer without the size tag  ` width="300" height="300"`. Do you like the result? Do you want what is doing on?
Setting the size on the SVG tag and setting control size are two different things.

Setting the size (width, height) on the SVG tag itself sets the output image size, the SVG is rendered to that size.
That does not determine the size of a WPF control, if not explicitly set it is controlled by the container.

If you do not have control over the SVG image size, but wish to maintain a fixed size of your control, set the control size and the stretch to `UniformToFill`.

**Comment by ohurskyi** [comment]
@paulushub Got it.

For the next `SVG`
```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" viewBox="-800 -800 1600.00 1600.00">
  <g id="test-group">
    <circle cx="0" cy="0" r="20" fill="turquoise"/>
  </g>
</svg>
```

To achieve the same display output as in the online viewer (`SVG width and height` was set to `300`)
![Svg_With_Circle_In_Center](https://user-images.githubusercontent.com/53793275/101186532-dea1c680-365b-11eb-845c-b52632a3b1a6.PNG)

In `SvgViewbox` control I should do the next
```
<Window Height="450" Width="800">
    <Grid>
        <svgc:SvgViewbox Width="300" Height="300" Stretch="UniformToFill">
            <svgc:SvgViewbox.SvgSource>
                <![CDATA[
                  <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" viewBox="-800 -800 1600.00 1600.00" >
                  <g id="test-group">
                    <circle cx="0" cy="0" r="20" fill="turquoise" />
                  </g>
                 </svg> 
                 ]]>
            </svgc:SvgViewbox.SvgSource>
        </svgc:SvgViewbox>
    </Grid>
</Window>
```
Yes, or I am wrong?

**Comment by ohurskyi** [comment]
Got it, thank you for the quick response.
Is it possible to **Stretch** the entire `SVG viewbox` not only the element inside it **(circle element will be used as an example)**, using `SvgViewbox` control?
So for the next `SVG`
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="-800 -800 1600 1600" >
  <g id="test-group">
  <circle cx="0" cy="0" r="20" fill="turquoise" />
  </g>
</svg> 
```
In the `WPF` we will have the same output as [https://www.dropbox.com/s/a7wgc023tlygdv3/Small_Circle_In_Center.svg?dl=0](small circle in the center). using `SvgViewbox` with `Stretch="Uniform"`

The only way I was able to achieve this - is to add `rectangle` which defines the same region as `SVG viewbox`
```
<Grid>
 <svgc:SvgViewbox Stretch="Uniform">
  <svgc:SvgViewbox.SvgSource>
    <![CDATA[
     <svg xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="-800 -800 1600 1600" >
       <g id="test-group">
        <circle cx="0" cy="0" r="20" fill="turquoise" />
        <!-- Without this rectange circle element stretches to fill the whole size ! -->
        <rect x="-800" y="-800" height="1600" width="1600" style="fill:transparent;stroke:black"/>
       </g>
     </svg> 
   ]]>
 </svgc:SvgViewbox.SvgSource>
 </svgc:SvgViewbox>
</Grid>
```
Is it the only way how to do this?

**Comment by paulushub** [comment]
> Is it the only way how to do this?

An equivalent settings is available for the converters but not exposed by the controls, `EnsureViewboxSize`.
The `AutoSize` property may help but not what you need.

For now, you can extend the `SvgViewbox` control and override the protected method below to set that property to true.
```
protected virtual DrawingGroup CreateDrawing(string svgSource, WpfDrawingSettings settings)
{
}
```

**Comment by ohurskyi** [comment]
Works.
Thank you for helping me to find the solution!

**Comment by TruePluto** [comment]
thank you  [paulushub](https://github.com/paulushub) 
but I do not know how to code.
```
protected virtual DrawingGroup CreateDrawing(string svgSource, WpfDrawingSettings settings)
{
}
```
thank you [ohurskyi](https://github.com/ohurskyi)
`<rect x="-800" y="-800" height="1600" width="1600" style="fill:transparent;stroke:black"/>
`   
it is ugly but effective and it have a white background and a black border
