### ISSUE TITLE
How is it possible to render a element when its style or fill attribute is changed?

### ISSUE THREAD

**Issue by paulushub** [ElinamLLC/SharpVectors#184]
In a SvgPictureBox, I need to dynamically change the colors of svg elements based on realtime data. For example :
```csharp
myElement.SetAttribute("fill", "#00FF00"); 
// or 
myElement.SetAttribute("style", "fill: #00FF00");
```
But the change is not rendered in the SvgPictureBox instance.
Is there any other solution to change these attributes? or should I call a method to render after the change ? Thanks for any help

_Originally posted by @pierreandreline in https://github.com/ElinamLLC/SharpVectors/discussions/183_

**Comment by pierreandreline** [comment]
I managed to build the library after last commit. And it works !

Here's the code of the test (.net 4.0 target) : 

```csharp
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        SvgPictureBox svg = new SvgPictureBox();

        private void Form1_Load(object sender, EventArgs e)
        {
            this.Controls.Add(svg);
            svg.Load(@"rect.svg");
        }

        private void button1_Click(object sender, EventArgs e)
        {
            // Set rectangle color to green
            SvgElement r = svg.Window.Document.GetElementById("r") as SvgElement;
            r.SetAttribute("fill", "#00FF00");
            svg.Refresh();
        }
    }
```
And the ```rect.svg``` file :

```xml
<?xml version="1.0" encoding="utf-8"?>
<svg xmlns="http://www.w3.org/2000/svg">
  <rect id="r" x="20" y="20" width="100" height="100" fill="#FF0000"/>
</svg>
```

So I have to call the **Refresh** method of the ```SvgPictureBox``` object after an attribute change.
Is that correct ? Or should I use another method from the element that was changed ?
Thanks again

**Comment by paulushub** [comment]
@pierreandreline Yes, the `Refresh` method clears the cached drawing and redraws the document. The `Invalid` or `Update` methods only updates the screen from the cached drawing.

**Comment by pierreandreline** [comment]
Is there a way to optimize attributes changes ? When I load a SVG file with many compondents (30 components for example), then when I call the **Refresh()** method, is well redesigned but with a flashing feeling, I mean the svg picture disappears and reapppears in a very short time. So is it possible to refresh only region of the component which is changed or a another way to avoid *flashing* felling ? Thanks for your help.

**Comment by paulushub** [comment]
@pierreandreline Refreshing the invalid region will be the natural thing to do. However, with SVG, it can be difficult to handle due to element referencing. Below is an example from the SVG spec [11_01.svg](https://www.w3.org/TR/SVGTiny12/examples/11_01.svg)
```svg
<?xml version="1.0"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.2" baseProfile="tiny"
     width="7cm" height="2cm" viewBox="0 0 700 200">

  <desc>Gradients apply to leaf nodes</desc>

  <g>
    <defs>
      <linearGradient xml:id="MyGradient" gradientUnits="objectBoundingBox">
        <stop offset="0" stop-color="#F60"/>
        <stop offset="1" stop-color="#FF6"/>
      </linearGradient>
    </defs>

    <rect x="1" y="1" width="698" height="198" fill="none" stroke="blue" stroke-width="2"/>

    <g fill="url(#MyGradient)">
      <rect x="100" y="50" width="200" height="100"/>
      <rect x="400" y="50" width="200" height="100"/>
   </g>
  </g>
</svg>
```
If I change the color of the gradient brush (**MyGradient**), all elements referencing that will be affected and must be repainted. This can get tricky with painting only the invalid region.
That said, I am open for any idea or suggestion to make this possible and usable. I will also be looking into the possibilities. One possible solution is to let the user specify the invalid region.

**Comment by pierreandreline** [comment]
@paulushub thank you for this precise answer. I understand. I my case, the goal is to change colors, visibilities and text according to real time data. For example, a color corresponds to a state of a equipment (off, on or error). So I only need to change each specific svg element instance (mostly rectangles, circles et paths), and not attributes in symbols defined in ```defs``` node. But I understand it's not easy de determine the exact region of a element, and also that my request is a probably too specific to be managed in a generic library.
Anyway and as you adviced, I'll try to invalidate the element region to check if it meets my need. I'll keep you informed. Thanks again !

**Comment by paulushub** [comment]
@pierreandreline The WPF version could be a better candidate for such purpose, since the rendered drawing is still a vector and could easily be modified and animated.
This library is a by-product of similar work I did for vehicle wiring system visualizations, and I used the WPF renderer. That is why it is more matured than the GDI+ renderer.

Even with the GDI+, there is a map of the screen graphics objects and SVG elements, so such specific need can be achieved through custom control.
If you have control over the SVG files, the target elements to be modified can be put into a separate layer (**`<g>`** element), this top layer can be changed without changing the whole drawings.
If you can provide samples (**that does not leak your company specifics**, sketch the SVG yourself with enough information to cover your specific needs), we could work on it together and I will release it as sample.
