### ISSUE TITLE
e notatation seems not to be supported

### ISSUE THREAD

**Issue by UkooLabs** [ElinamLLC/SharpVectors#185]
I have attached a zipped svg that was generated from an adobe product that generates an error with library the element in question is 
```xml
<linearGradient id="SVGID_1_" gradientUnits="userSpaceOnUse" x1="54.9239" y1="71.7029" x2="88.4794" y2="71.7029">
	<stop  offset="2.520161e-04" style="stop-color:#81BAE5"/>
	<stop  offset="1" style="stop-color:#82BAE5"/>
</linearGradient>
```
It seems to think e notation of 2.520161e-04 is not in range  of 0-1

[LOGO_Lotus_Yoga_Blue.zip](https://github.com/ElinamLLC/SharpVectors/files/6327388/LOGO_Lotus_Yoga_Blue.zip)

**Comment by paulushub** [comment]
@UkooLabs The stop is correctly parsed. The color blend must start from 0.0, not the stop value of **0.0002520161**. 
After parsing, for the GDI+, this must be checked and fixed.
