### ISSUE TITLE
SvgViewbox ignores the whitespace around the image

### ISSUE THREAD

**Issue by jgrossrieder** [ElinamLLC/SharpVectors#190]
Hi,

I've 2 SVG that I want to overlay.

One is the main image, always displayed, taking the full height/width.
The second one(linked) is only on the bottom of the image. But when I superpose them, it gets displayed on the middle:

```xml
<Grid>
  <svgc:SvgViewbox Source="SingleExpansionCollar.svg"  />
  <svgc:SvgViewbox Stretch="None" Source="SingleExpansionCollarBottom.svg"
         Visibility="{Binding IsBottomPartVisible, Converter={StaticResource BooleanToVisibilityConverter}}"/>   
</Grid>
```
Is there a way to have the second image(...Bottom.svg) that takes the full space without trimming the whitespace?

[CollarSingle.zip](https://github.com/ElinamLLC/SharpVectors/files/6539843/CollarSingle.zip)

**Comment by paulushub** [comment]
@jgrossrieder Please, can you draw an picture/illustration of how you want the final result to look like? Just render each, copy the screenshots and position with any drawing application like MS-Paint.
