### ISSUE TITLE
Cannot use SharpVectors with Fody.Costura

### ISSUE THREAD

**Issue by MihailsKuzmins** [ElinamLLC/SharpVectors#199]
In one of my projects I use Fody.Costura to generate a single file and SharpVectors to render svg images, but it looks like SharpVectors library is not compatible with Fody.Costura because in many places `assembly.Location` is used. Fody.Costura does not tolerate it (https://github.com/Fody/Costura/issues/251#issuecomment-524191388)

I have looked at usages of `assembly.Location` and it looks like only the executing or entry assembly is used. Therefore, there is a workaround. It is possible to use `AppDomain.Current.BaseDirectory`. AppDomain is compatible with Fody.Costura and produces the same output as `assembly.Location`.

So, could it be possible to use `AppDomain.Current.BaseDirectory` instead? If you find it difficult, I could try to prepare a PR 😃.

それでは、素敵なパッケージ、ありがとうございます。よく使って、好きですよ。お手伝いが必要だったら、教えてくださいませんか。

よろしくお願いします。
ミシャ。

**Comment by paulushub** [comment]
> よく使って、好きですよ。お手伝いが必要だったら、教えてくださいませんか。

ありがとうございます。確認します。まず「Fody/Fody.Costura」について。

**Comment by MihailsKuzmins** [comment]
その問題の為の「PR」の支度ができました。 @paulushubさん、見てもらえませんか。
「PR」の番号は #200 です。

**Comment by MihailsKuzmins** [comment]
お久しぶりですね。
@paulushubさん、いつNuGetパッケージを変更しますか。この変更を持っているのですから。
とりあえず、「submodule」を使っていますが、ビルドは数分をかかります。便利じゃないですよね。:cry:

**Comment by paulushub** [comment]
@MihailsKuzmins 申し訳ありませんね！NuGetパッケージを更新しました。

**Comment by MihailsKuzmins** [comment]
> @MihailsKuzmins 申し訳ありませんね！NuGetパッケージを更新しました。

@paulushubさん、謝らなくてもいいです。NuGetパッケージを更新してくれて、ありがとうございました。お疲れ様でした。
