### ISSUE TITLE
Svg not visible in the editor window

### ISSUE THREAD

**Issue by Filippoml** [ElinamLLC/SharpVectors#220]
Works on Visual Studio 2019
![image](https://user-images.githubusercontent.com/14567796/147500105-87eceb35-9350-444c-8a10-fcd538983a31.png)

Doesn't work on Visual Studio 2022

![image](https://user-images.githubusercontent.com/14567796/147500084-c90e40cb-7b54-47b1-b20a-7db2f8833c4d.png)

**Comment by paulushub** [comment]
Thanks for the information. The designer application in VS2022 is likely changed, and we will have to look for and support the new designer.
There is an on-going work to move the projects to VS2022 and support .NET 6.x. Hopefully, this will be released in the next version.

**Comment by paulushub** [comment]
@Filippoml Please can you verify this again with the sources in the repository. 
Just viewed an XAML in the VS 2022, and tab images are displayed in the design mode.

**Comment by a-kriya** [comment]
@paulushub Hi. I see that you added support for 6.0 in 82ff2da. Can you please suggest how I can use this version? 1.7.7 was released a while ago. Do you have plans to release a newer version with support for 6.0 soon? Thanks.

**Comment by paulushub** [comment]
@a-kriya Sorry for the delay. Version 1.8 is scheduled to be released within this month. I have almost completed the `ResourceDictionary` converter, the remaining feature marked for this release.

**Comment by a-kriya** [comment]
@paulushub It's all good, thank you for the response. That sounds great.

**Comment by paulushub** [comment]
We have finally resolved this issue with the current update to the repository.

**Comment by nikitoSha** [comment]
Hi! Sorry, but I have the same issue (VS v17.3.2, NET Framework is 4.8.04161):
![Screenshot_207](https://user-images.githubusercontent.com/15741303/189083207-375ac8a6-ed95-48a3-9232-8ef92c2f3641.png)

**Comment by paulushub** [comment]
@nikitoSha This improved feature is not yet released, only available in the repository.

**Comment by nikitoSha** [comment]
> @nikitoSha This improved feature is not yet released, only available in the repository.

Do you know, ho much time you need for release and send to nuget?
If you haven't any time, I will download from repo. Thanks

**Comment by paulushub** [comment]
> Do you know, ho much time you need for release and send to nuget?

I will look into it - normally update is driven by demand or features. There was also a demand for the `SvgIcon` in the repository.

**Comment by paulushub** [comment]
@nikitoSha Release 1.8.1 is available.

**Comment by nikitoSha** [comment]
> @nikitoSha Release 1.8.1 is available.

You are the best, thanks

**Comment by dojo90** [comment]
I still have the problem.
VisualStudio v17.4.4
SharpVectors v1.8.1
`    <TargetFramework>net6.0-windows10.0.19041</TargetFramework>`
