### ISSUE TITLE
Dashed line looks different compared to other tools

### ISSUE THREAD

**Issue by Skleni** [ElinamLLC/SharpVectors#223]
I have an SVG file that is displayed differently when using this library compared to other tools:

```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 100 20">	
	<line x1="10" y1="10" x2="90" y2="10"
		  style="stroke: #000; stroke-dasharray: 0 5; stroke-linecap: round"/>
</svg>
```

SharpVectors:

![image](https://user-images.githubusercontent.com/10420514/168743945-e6c27dfe-6095-4cb3-a21d-934dd5dac8b4.png)

Other tools like browsers or [svgviewer.dev](https://www.svgviewer.dev/):

![image](https://user-images.githubusercontent.com/10420514/168744034-e24f95e7-4eab-45d6-9ce4-01ce3c996d1c.png)

After some experiments I think the combination of `stroke-linecap: round` and having a `0` in the `stroke-dasharray` is what causes the discrepancy.

**Comment by paulushub** [comment]
Simply a GDI+ limitation assumed on WPF, which actually renders this correctly.

**Comment by Skleni** [comment]
Thanks!
