### ISSUE TITLE
missing text in converter result (SharpVectors.Converters.FileSvgReader.DrawingGroup)

### ISSUE THREAD

**Issue by aaronnottbeck** [ElinamLLC/SharpVectors#226]
i am trying to convert SVGs to a XAML DrawingGroup using the above Converter.
Sometimes text elements wont get transformed into  the result.

Sample:
Excel_Export.svg - text gets converted
RIB_Import_DataFromTXT.svg no text converted
test.xaml.txt result xaml dictionary

I am using 
https://github.com/BerndK/SvgToXaml
to convert the SVGs.
I debugged the code and it seems hat the error occures in the SharpVectors code.

[test.xaml.txt](https://github.com/ElinamLLC/SharpVectors/files/9475307/test.xaml.txt)
![Excel_Export](https://user-images.githubusercontent.com/3070852/188070712-54725809-d310-4d2b-aada-3b2f0e59ebc2.svg)
![RIB_Import_DataFromTXT](https://user-images.githubusercontent.com/3070852/188070715-c5a8f8f7-efeb-4fe9-93c9-e715a9f8a9cd.svg)

**Comment by paulushub** [comment]
@aaronnottbeck Please post the SVG file for testing.

**Comment by paulushub** [comment]
@aaronnottbeck OK, your SVG test file is embedded in the post. The test result is shown below and there seems to be no problem in SharpVectors.

![test1](https://user-images.githubusercontent.com/809351/188077643-763ad9a0-d226-436c-a3c0-d0ef285f8f66.jpg)

If you want the [BerndK/SvgToXaml](https://github.com/BerndK/SvgToXaml) style `ResourceDictionary` output, it is recently added to the SharpVectors. Either use the library directly,`ResourceSvgConverter`, or use the `WpfTestResourceSvg` sample.

**Comment by aaronnottbeck** [comment]
thank you for testing - i'll take a look on WpfTestResourceSvg

**Comment by aaronnottbeck** [comment]
one additional question: do you already have prepared a projectfile for VS22 and net6?
