### ISSUE TITLE
Zoom issue when create new page in new window

### ISSUE THREAD

**Issue by abdou31** [ElinamLLC/SharpVectors#238]
I have an svg window like DrawingPage.xaml in the sample of library and I'm loading on it an svg , when I do a resize to the window the svg scaled to the window perfectly but when I reload the svg in the window ( create new svg drawing page ) .

It will have a small size and it will be not zoom on.

How can I fix this?

```csharp
   drawingPage= null;
   myviewBox.Children.Clear();

   if (Type == "svgFormat")
   {
        drawingPage= new DrawingPage();

        RefreshDrawingPage();
        myviewBox.Children.Add(drawingPage);
   }


  public void RefreshDrawingPage()
        {
            if (drawingPage.zoomPanControl != null && drawingPage.Viewer != null)
            {
                drawingPage.Viewer.InvalidateMeasure();
                drawingPage.Viewer.UpdateLayout();

                Rect bounds = drawingPage.Viewer.Bounds;

                if (bounds.IsEmpty)
                {
                    bounds = new Rect(0, 0, drawingPage.Viewer.ActualWidth, drawingPage.Viewer.ActualHeight);
                }

                //zoomPanControl.AnimatedZoomTo(bounds);
                drawingPage.zoomPanControl.AnimatedZoomTo(drawingPage.FitZoomValue);
                CommandManager.InvalidateRequerySuggested();
            }
        }

**Comment by paulushub** [comment]
@abdou31 Your application structure is not very clear. 
For instance, this line `myviewBox.Children.Add(drawingPage);` suggests you are adding a `Page` object to a `Viewbox` control, which is not normally done.

Please can you post a simple sample application to demonstrate your use case?

**Comment by abdou31** [comment]
I can't post the hole code , but I will explain to you .  

The `drawingPage` is a `UserControl `that have the `svgPath `and `zoomPanControl ` , this user control will be loaded in another `UserControl` called `DisplaySvg `, in particular , it will be added to a `ViewBox` , when I do the resize to the window , the `drawingPage` follow the resize and have a new width and height in every firing of the event `OnPageResizing` and this is good , I will have the svg filled to the parent window .

The problem is that when I redraw the svg , I have some parameters of paths to change for example in Combobox .

And when I do a new redraw , I didn't get the scale behavior to the parent window , the SVG will be in small size .

Have you any idea to resolve this?

**Comment by paulushub** [comment]
> I can't post the hole code , but I will explain to you .

With WPF, I thought it will be easy to create a **simple demo application** and attach it for discussion, without having to post your actual application codes.
Trying to create a memory visual image of your use case from the description will be time consuming and difficult.

**Comment by abdou31** [comment]
@paulushub   , I solved my problem , thank you for your support , however , I've added the code the OnPageSized event in the PageLoad event , and the zoom issue of loading is solved now.
