### ISSUE TITLE
Not render after update from v1.8.0 to v1.8.1

### ISSUE THREAD

**Issue by emako** [ElinamLLC/SharpVectors#240]
```xaml
<svgc:SvgViewbox Margin="0,0,0,0" Opacity="0.9" Width="28" Height="28" IsHitTestVisible="True" Source="../Resources/squircle.svg" VerticalAlignment="Center" HorizontalAlignment="Center"/>
<svgc:SvgViewbox x:Name="SvgViewBoxMainIcon" Margin="0,0,0,0" Opacity="0.9" Width="18" Height="18" IsHitTestVisible="True" Source="../Resources/geo.svg" VerticalAlignment="Center" HorizontalAlignment="Center"/>
```

What's the diff between v1.8.0 and v1.8.1?

**Comment by emako** [comment]
> v1.8.0
![image](https://user-images.githubusercontent.com/24737061/206547810-6dfa9f5d-fded-43a8-bea6-f3cd7e5788e5.png)

---
> v1.8.1
![image](https://user-images.githubusercontent.com/24737061/206547691-7145ef01-2628-4ee4-a454-44d1b2dea028.png)

**Comment by paulushub** [comment]
@emako Sorry for the delay. Please if possible, can I have a copy of the SVG file that is failing for test?
BTW, for icons I will recommend either the SvgIcon control or the SvgImage markup.

**Comment by emako** [comment]
Here my [repository](https://github.com/genshin-matrix/genshin-woodmen).
Updated `SharpVectors` to v1.8.0 and it will be reproduced.
```xaml
  <ItemGroup>
    <PackageReference Include="SharpVectors" Version="1.8.1" />
  </ItemGroup>
```

**Comment by emako** [comment]
SVG file [here](https://github.com/genshin-matrix/genshin-woodmen/blob/main/src/GenshinWoodmen/Resources/dendro.svg)

**Comment by LoriBru** [comment]
Hello, I have the same issue in my application.
v1.8.0 works fine while in 1.8.1 no icons are displayed using the SvgViewbox control.

**Comment by paulushub** [comment]
@LoriBru Thanks for the feedback. 
I have reproduced the issue with @emako codes, but do not yet know why, as the test SVG file is correctly rendered by the `WpfSvgTestBox` sample. Hope to resolve it soon.

**Comment by Dealman** [comment]
I'm having a similar issue, not sure what's going on - maybe some caching issue? It was working just fine for me, so I kept working on other stuff and later noticed the SVGs had stopped rendering.

Been testing a bunch of stuff and tried reverting some code - no matter what I've tried, I have been entirely unable to get any SVG file to render again.

**Comment by Wildcatii** [comment]
`<svgc:SvgIcon Fill="Red" UriSource="Resources\Svg\InStock.svg"  Width="16" Height="16" />`
work for me.

**Comment by paulushub** [comment]
@Wildcatii  Thanks for the update. The `SvgSource` property is not used like that but for direct SVG contents input (see the [documentations ](https://elinamllc.github.io/SharpVectors/articles/controls.html) for illustrations)
```xml
<svgc:SvgViewbox x:Name="embeddedSvgViewbox" HorizontalAlignment="Center" VerticalAlignment="Center">
<svgc:SvgViewbox.SvgSource>
    <![CDATA[
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
<circle fill="#009" r="45" cx="50" cy="50"/>
<path d="M33,26H78A37,37,0,0,1,33,83V57H59V43H33Z" fill="#FFF"/>
</svg>
    ]]>
</svgc:SvgViewbox.SvgSource>
```

**Comment by paulushub** [comment]
No reproducible sample. If you still experience this, please post a sample.
