### ISSUE TITLE
Svg file render wrong. 

### ISSUE THREAD

**Issue by kikokuo** [ElinamLLC/SharpVectors#243]
Hi 
     Some svg file not  correct to render. If I using IgnoreRootViewbox of WpfDrawingSettings, it work, but I also need EnsureViewboxSize  of WpfDrawingSettings to show other svg files. So, 
    Can we have any flag or solution to solve this situation?
    I also attached file to help to check this sutiation.
    Thanks.
[20230109164025.zip](https://github.com/ElinamLLC/SharpVectors/files/10389876/20230109164025.zip)

**Comment by kikokuo** [comment]
Hi,
    After test new commit, it correct render. Thanks for your help.

**Comment by paulushub** [comment]
The fix is wrong and existing codes: Issue #267 
I have reworked this issue for a better rendering of the viewbox.

**Comment by paulushub** [comment]
@kikokuo Reworked this issue, it should work better now. Please verify the result with the latest commit.

**Comment by kikokuo** [comment]
Hi,
After test new commit, it correct render. thanks again.
