### ISSUE TITLE
Why can't it be displayed in design mode

### ISSUE THREAD

**Issue by BluePointLilac** [ElinamLLC/SharpVectors#245]
The VS2022 design mode does not support the use of short paths to display Svg. It can only be displayed when I pass in the full path. 

Short path like:
`<svgc:SvgViewbox Source="../Resources/Svgs/MySvg.svg"/>`

Full path like:
`<svgc:SvgViewbox Source="pack://application:,,/MyDll;component/Resources/Svgs/MySvg.svg"/>`

**Comment by SamKr** [comment]
+1

**Comment by paulushub** [comment]
It seems the files are in a different component `MyDll`. In such cases, use the `AppName` to specify the component name.
