### ISSUE TITLE
SvgViewbox LoadAsync Exception: System.InvalidOperationException

### ISSUE THREAD

**Issue by hsiaoho** [ElinamLLC/SharpVectors#249]
Xaml content:
![image](https://user-images.githubusercontent.com/3917639/226170907-e89f9309-351c-4d89-a095-3e66d0656705.png)
![image](https://user-images.githubusercontent.com/3917639/226170949-2c2d24ed-5263-4328-9a4b-1adbb3b5d9d8.png)

Exception row:
![image](https://user-images.githubusercontent.com/3917639/226171065-ea8bc90e-ac81-4f96-a762-a0f3447a032e.png)
![image](https://user-images.githubusercontent.com/3917639/226171137-1073fbcc-bfe8-417d-972d-b2fa66519e72.png)

the same exception exists for SvgBitmap, SvgCanvas, SvgControl

**Comment by paulushub** [comment]
SvgBitmap does not contain the LoadAsync method. Also, this method is awaitable, so use the async/await.
