### ISSUE TITLE
SvgViewbox can not open this Uri(https://baikebcs.bdimg.com/cms/static/baike-icon.svg)

### ISSUE THREAD

**Issue by wiener2015** [ElinamLLC/SharpVectors#254]
In my project, 
SvgViewbox can not open this Uri 
https://baikebcs.bdimg.com/cms/static/baike-icon.svg
but this uri can be opened normally with browser
why?
Did I do anything wrong?

**Comment by paulushub** [comment]
It is rather a binary format. What format is it?

**Comment by wiener2015** [comment]
I do not kown the format.
it comes from the internet and can be opened normally with browser.

**Comment by paulushub** [comment]
SVG and a text format, the binary version is SVGZ, which is gz encoded.
I do not know if the new specification allows other encoding.
Currently, SharpVectors cannot recognize the encoding of that file.

**Comment by wiener2015** [comment]
I see, it is gzip encoded
I hope SharpVectors can support this format earlier or provide some kind of converter
thanks for the reply!
