### ISSUE TITLE
Rendering issue with elements outside the canvas

### ISSUE THREAD

**Issue by mirabyte** [ElinamLLC/SharpVectors#267]
With the latest update from v1.8.1 to v1.8.2, there is a new issue with rendering SVG files (in WPF) when elements of the SVG are outside the canvas of the image. An example image is attached. When rendered in WPF, the origin of the elements is not set correctly, but reverts to 0|0, resulting in an incorrectly rendered image.

![burst](https://github.com/ElinamLLC/SharpVectors/assets/7288505/ab81e805-cb2e-493f-8607-c1506f4a1727)

**Comment by paulushub** [comment]
@mirabyte I have observed changed from due to "Ensure Viewbox Position" is affecting the rendering of this file.
If that is the case and it is will not affect other images, then set the **EnsureViewboxPosition** property to false.

**Comment by paulushub** [comment]
@mirabyte I have now resolved this issue in the latest commit, please verify the result.

**Comment by mirabyte** [comment]
Looks good. We previously worked around by setting **EnsureViewboxPosition** to false as advised. So this is not needed any more and we can set back to the previous state. Thanks!
