### ISSUE TITLE
Not Support the extra commas in SVG elements

### ISSUE THREAD

**Issue by Zhao-Michael** [ElinamLLC/SharpVectors#274]
My svg comes from [LiveCharts2](https://github.com/beto-rodriguez/LiveCharts2).

For example:  x="155.06738, 163.50488, 171.19238, 178.0127, 182.02051, 188.30176, 195.12207, 201.75488, 206.44238, 211.99707, " 

It will throw an exception in SvgLengthList :: FromString :: throw new DomException(DomExceptionType.SyntaxErr);

I believe Edge browser support it. would you please support this svg content?

Thanks!

**Comment by paulushub** [comment]
Browsers are generally more forgiving, could be trimmed. Can you provide a complete sample for testing?

**Comment by Zhao-Michael** [comment]
Try this one. maybe caused by SkiaSharp...

![test](https://github.com/ElinamLLC/SharpVectors/assets/15730936/5d03e323-ca33-475e-9eeb-1a67b1f5966d)

**Comment by paulushub** [comment]
@Zhao-Michael OK! It is fixed, there is a already a trim, but I added extra trim for comma, in order not to miss the previous trim of whitespace (with UNICODE support). Should be available soon.
![image](https://github.com/ElinamLLC/SharpVectors/assets/809351/b258ea24-1036-47cc-88d9-07daa3a5179f)

**Comment by Zhao-Michael** [comment]
Good Job! Thanks.
