### ISSUE TITLE
Release New version schedule?

### ISSUE THREAD

**Issue by kikokuo** [ElinamLLC/SharpVectors#276]
Hi @paulushub 
     Latest version have  bugs like #273 and #274, but you already fixed it, so, would you have schedule to release new version?
     thanks @paulushub

**Comment by paulushub** [comment]
@kikokuo Sorry for the delay. Trying to create GitHub repositories to host each on the libraries used the test applications (`Libraries` folder), so that I can delete that folder to reduce repository size.
I agree this is taken too much time, will look into release now, and others later.
