### ISSUE TITLE
EnsureViewboxSize of WpfDrawingSettings not work when svg has viewbox.

### ISSUE THREAD

**Issue by kikokuo** [ElinamLLC/SharpVectors#277]
Hi, @paulushub 
        The latest vesion has a bug, when svg has viewbox, the ensureViewboxSize of WpfDrawingSettings not work. 
        Could you help to check it? thank you.
[20220704102345692.zip](https://github.com/ElinamLLC/SharpVectors/files/13944465/20220704102345692.zip)

**Comment by paulushub** [comment]
@kikokuo What is your expectation? What is wrong with the output?
With the improved support for `viewbox`, the property `EnsureViewboxSize` is no more needed.
`EnsureViewboxSize` was only introduced a clip region defined by `viewbox` that was not effective, and was causing issues in some cases.
