### ISSUE TITLE
Size of drawinggroup is not correct in 1.83

### ISSUE THREAD

**Issue by ehtick** [ElinamLLC/SharpVectors#278]
After upgrading from 1.60 to 1.83 i saw in my wpf application that the SVG loaded are shown larger.

Debugged the change and found that in the sample   SvgXaml, the following line

_drawing = _fileReader.Read(_sourceFile, _outputInfoDir);

return a different size from the 2 versions.

<?xml version="1.0" encoding="UTF-8"?>
<svg width="120mm" height="260mm" version="1.1" viewBox="0 0 120 260" xmlns="http://www.w3.org/2000/svg" xmlns:cc="http://creativecommons.org/ns#" 

even setting the EnsureViewboxSize to true does not help. the old version return the correct size 120x260 and the new version a strange larger number.

**Comment by CustomBrandCo** [comment]
I have just experienced the same thing. Updated from 1.81 to 1.83 and drawings are not coming out the correct size anymore. I have EnsureViewboxSize set to true.

Seems to be working in 1.82.

**Comment by paulushub** [comment]
> I have EnsureViewboxSize set to true.

With the update to the viewbox in 1.8.3, the `EnsureViewboxSize` property is no longer needed.

@ehtick @CustomBrandCo Please post a sample image for verification. 
The `EnsureViewboxSize` was only adding a clip region, which was not working in some cases.

**Comment by CustomBrandCo** [comment]
I have set up a simple WPF .net 8.0 project with the following code in the main window.

I have attached screen shot of output in version 1.8.2 (first image) and 1.8.3 (second image). As you can see, 1.8.2 has space around as expected, 1.8.3 does not.

I have also attached the SVG file that I used.

`<Window x:Class="SharpVectors.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:SharpVectors"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800" Loaded="Window_Loaded">
    <Grid Background="Gray">
        <Viewbox Margin="10">
            <Canvas Width="1511.8110236220472440944881889764" Height="1700.7874015748031496062992125984" Background="White"  >
                <Image x:Name="MyImage" Canvas.Left="0" Canvas.Top="0" 
                       Width="1511.8110236220472440944881889764" Height="1700.7874015748031496062992125984" />
            </Canvas>
        </Viewbox>
    </Grid>
</Window>
`

` public partial class MainWindow : Window
 {
     public MainWindow()
     {
         InitializeComponent();
     }
     public ImageSource? GetSvg()
     {
         using var fs = File.OpenRead(@"C:\.......\Art2.svg");
         using var ms = new MemoryStream();
         using var converter = new StreamSvgConverter(new WpfDrawingSettings
         {
             IncludeRuntime = true,
             TextAsGeometry = true,
             EnsureViewboxSize = true
         });
         var output = !converter.Convert(fs, ms)
             ? null : new DrawingImage(converter.Drawing);
         return output;
     }
     private void Window_Loaded(object sender, RoutedEventArgs e)
     {
         MyImage.Source = GetSvg();
     }
 }`

![SharpVectors 1-8-2](https://github.com/ElinamLLC/SharpVectors/assets/143000246/21957167-9344-4b81-9cdd-41c75e52793e)
![SharpVectors 1-8-3](https://github.com/ElinamLLC/SharpVectors/assets/143000246/f8478562-9e4c-4613-b5af-d845576b9967)

![Art2](https://github.com/ElinamLLC/SharpVectors/assets/143000246/d8696f9f-80bf-40c0-8482-f5bdf1488663)

**Comment by ehtick** [comment]
Hey thanks for the sample, just wanted to create one :)

Please look good at the bounds, 1.60 also gives different sizes then 1.82. 1 mm bigger.

**Comment by paulushub** [comment]
@ehtick @CustomBrandCo 
The version 1.83, changed the order of applying the viewbox, from the start of the rendering to the end of the rendering.
The rendered drawing is then adjusted accordingly. I understand your requirement to apply the transparent bounds, which give WPF a sense of dimension of the drawing.
Now, please verify the current commit and provide feedbacks.

**Comment by CustomBrandCo** [comment]
I have downloaded the current commit and used the resulting dlls in the same sample project as I created earlier.

It appears to have the correct spacing again. Thank you

![Screenshot 2024-02-06 113708](https://github.com/ElinamLLC/SharpVectors/assets/143000246/22bae85d-6ef7-44b3-bb36-150370c168bd)
.

**Comment by paulushub** [comment]
Yes, you have not provided your feedback.

**Comment by ehtick** [comment]
> Yes, you have not provided your feedback.

Sorry, my problems are also solved :)
