### ISSUE TITLE
MIT license text may be incorrect

### ISSUE THREAD

**Issue by DaveInCaz** [ElinamLLC/SharpVectors#280]
I noticed that in the MIT license section of https://github.com/ElinamLLC/SharpVectors/blob/master/License.txt the first few lines are the following:

> MinIoC License (https://github.com/microsoft/MinIoC)
> MIT License
> 
> Copyright (c) Microsoft Corporation. All rights reserved.
>...

But I would have thought it should read more like this:

> The MIT License (MIT)
> Copyright (c) 2010 - 2024, Elinam LLC
> ...

based on other usages of the MIT license I have seen. For example: https://github.com/JamesNK/Newtonsoft.Json

Thanks

**Comment by paulushub** [comment]
> But I would have thought it should read more like this:

My understanding: `Newtonsoft.Json` is licensed under MIT.

MinIoC in SharpVectors is still in its own license, MIT.
It is copied verbatim (like that of Brotli), as is the practice for third-party licenses listing.

**Comment by DaveInCaz** [comment]
@paulushub I understand now. My mistake was that I misinterpreted the intent of the License.txt file. I thought it was supplying several alternative licenses all for SharpVectors rather than first providing the SharpVectors license, and then secondly attributing other third-party components. (There are occasionally projects which do offer multiple licenses). 

Thanks for the explanation, sorry for taking up your time!

**Comment by DaveInCaz** [comment]
@paulushub  I just noticed there are actually two license files in the repo:

https://github.com/ElinamLLC/SharpVectors/blob/master/License.md
and
https://github.com/ElinamLLC/SharpVectors/blob/master/License.txt

Both have the BSD license for SharpVectors itself, and the second one also has the third-party attributions.

As a suggestion, it might be less confusing (for dummies like me 😁) if you removed the BSD part from the second file and use it only for third-party attributions.

Also, the BSD sections have different copyright dates.

**Comment by paulushub** [comment]
> Both have the BSD license for SharpVectors itself, and the second one also has the third-party attributions.

The `License.md` is meant for Github users, who simply want to know the license of the code. 
The `License.txt` is used in the Nuget packages: https://github.com/ElinamLLC/SharpVectors/blob/a0272a4029e8e329895bd995ea00fa347fe9d7ea/Source/SharpVectors.nuspec#L308


> Also, the BSD sections have different copyright dates.

Thanks, I will update that. Licensing is an important issue, I do appreciate you looking into it.

**Comment by DaveInCaz** [comment]
The one meant for Nuget may actually be messing up the GitHub logic. When you view the main SharpVectors page, it shows this in the sidebar:
![image](https://github.com/ElinamLLC/SharpVectors/assets/18285074/677a4992-d923-45e1-84ea-1e909c382af3)

which if you click, shows this:
![image](https://github.com/ElinamLLC/SharpVectors/assets/18285074/e8b3a180-f994-4b3b-8a05-5499f1c306ff)

So its apparently picking up the Nuget file somehow. Maybe just based on filename?

This is partly what gave me the mistaken impression originally that you were offering multiple alternative licenses.

**Comment by paulushub** [comment]
It works well in the tab view, will look into any way to improve it.
![image](https://github.com/ElinamLLC/SharpVectors/assets/809351/1882613c-cec2-4707-a8d7-16aaeeaa5147)
