### ISSUE TITLE
SVGIcon not working correctly.

### ISSUE THREAD

**Issue by m0lDaViA** [ElinamLLC/SharpVectors#290]
Hello!

So as you can see the svgicon doesn't work at runtime, only in designtime and the SvgSource is .... weird?
I mean you can enter what you want, it doesn't matter, as long as you enter anything. If it is emtpy the svg is not visible in designtime.

Is there any other way to render svgs with the ability to change the color then svgicon?

![grafik](https://github.com/user-attachments/assets/412edf63-a0b9-441a-884a-bdcb4c9ee0ac)
![grafik](https://github.com/user-attachments/assets/9a60e269-c50d-4829-8a99-db646eba8eaa)

**Comment by paulushub** [comment]
Design-time is mainly loading from disk. 
Please make sure the file embedded in the resources for the runtime.

**Comment by m0lDaViA** [comment]
Well, it still doesn't work as resources, as embbeded as direkt file. Svgicon won't show it at all.
The markup svgimage does work but here you can't change the color.

**Comment by paulushub** [comment]
Post post a sample project with the file.

**Comment by m0lDaViA** [comment]
> Please post a sample project with the file.

So i created a test project and, as you probably suspected, it worked.
But not inside my main project and i don't see why.
I created a separated page with only the svg. It was created in designtime but not in runtime while in the test project it was created in both cases.

**Comment by paulushub** [comment]
I only suspected you are missing something and reproducing the issue in a sample project, I could find it.

**Comment by m0lDaViA** [comment]
> I only suspected you are missing something and reproducing the issue in a sample project, I could find it.

I would suspect that too tbh, but i can't miss anything here.
Plain and simple. Add the nuget, add the svgicon with UriSource. 1 works, 1 doesn't.
How  can i miss something there?
I mean i even tried different scenarios. With presenters, inside grid, inside stackpanel ect ect ...
The markup does work in both project but not the svgicon.

**Comment by paulushub** [comment]
Unfortunately, if you cannot reproduce the issue in a sample (I may also not be able), then it is specific to a project and cannot be easily resolved.

**Comment by paulushub** [comment]
I have still given it a shot and could not reproduce your issue. 
I tried it for a simply reason that the `SvgIcon` sample provided does not use resource file, and I might be missing something.
I tested with both `.NET 6` and `.NET 8`, just in case there is a framework issue.

Please take a look at the sample and compare it to your project.
[TestSvgIcons.zip](https://github.com/user-attachments/files/16479109/TestSvgIcons.zip)

**Comment by m0lDaViA** [comment]
So the question is "why"?
Why does it work in a simple project but not here?
What is the difference in usage? Or what is different if the usage is the same?
And why does the markup work everytime without any problem in every project i started?
I mean that should be always the case but why does it work while the svgicon does not?

**Comment by paulushub** [comment]
Unfortunately, I cannot tell what is happening in your project that I do not have access to.  If it is a SharpVectors issue, it should be reproducible in all cases.

**Comment by m0lDaViA** [comment]
Give me a moment. I have one thing in mind.

**Comment by m0lDaViA** [comment]
Ok i give up. I have no idea why it's not working there. I basically re-created the whole project and for some reason it's working there. I guess this is another VS issue for no reason...
