### ISSUE TITLE
Fill colour incorrect for certain rgb values in 1.8.4.1

### ISSUE THREAD

**Issue by RadtkeJCJ** [ElinamLLC/SharpVectors#291]
SharpVectors seems to be rendering colours like `rgb(255,0,1)` as `rgb(255,0,255)` - but `rgb(255,0,2)` works as expected. This also happens when the colours are specified as equivalent hex values. 1 seems to be a special case - looks like it might be related to the [change in 1.8.4.1](https://github.com/ElinamLLC/SharpVectors/commit/c84ca9bee7be8d3b68c8151b2bbb4592e4c3b868)? It was working as expected in 1.8.4.

Thanks :)

**Comment by paulushub** [comment]
@RadtkeJCJ Thanks for reporting, I have now fixed this bug - sorry.
