### ISSUE TITLE
SvgViewbox won't show SVGs with https scheme

### ISSUE THREAD

**Issue by denxorz** [ElinamLLC/SharpVectors#56]
The SvgViewbox control does not show SVG with an URI that starts with "https". It would be nice if it could do this (as more and more websites embrace https).

The following example won't show a image. 

```xml
<Window x:Class="WpfApp1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:svgc="http://sharpvectors.codeplex.com/svgc/"
        mc:Ignorable="d"
        Title="MainWindow" Height="350" Width="525">
    <Grid>
        <svgc:SvgViewbox Source="https://upload.wikimedia.org/wikipedia/commons/b/bd/Test.svg"/>
    </Grid>
</Window>
```

If I uncommented line 362 of SvgViewbox.cs, the image in the example above will be shown. I don't know the code well enough to know if this line can safely be uncommented. Same line appears to be commented as well in SvgCanvas.cs and SvgImageExtension.cs. 

I hope you can help me out.
Thanks!

**Comment by paulushub** [comment]
@denxorz Thanks for reporting this important issue. I am planning to restructure the whole project but will try and fix this by this weekend.

**Comment by paulushub** [comment]
Fixed the issue.

**Comment by denxorz** [comment]
It works. Thanks!
