### ISSUE TITLE
StreamSvgConverter.Convert is creating empty memory stream object when hosted.

### ISSUE THREAD

**Issue by Anoop1001** [ElinamLLC/SharpVectors#57]
I used your code to convert SVG data to PNG file. This code works fine if I use console application. But If I use it as a class library and referred the same in an asp.net application and execute in visual studio it is creating image without any issue. But if the app is hosted and executed then the image which is getting created is blank. There is no error also. Please help us.

Thanks & Regards,
Anoop H.N.

**Comment by paulushub** [comment]
Thanks for the updates. Someone is using it in a web application without any problem, but I cannot tell which converter he is using or which hosted system. Which is your hosted system (WebForms, MVC or WebAPI)?

**Comment by Anoop1001** [comment]
Thank you very much for the reply.

I tried with web forms but it did not work. Actually our project is based on MVC, 

1. We make an ajax call with encoded SVG data to service.
2. It is decoded at server side. It is converted to bytes array and then to memory stream.
   
byte[] svg = Encoding.ASCII.GetBytes(svgHtml);

WpfDrawingSettings ds = new WpfDrawingSettings();

```
using (StreamSvgConverter ssc = new StreamSvgConverter(ds))
{
	ssc.SaveXaml = false;
	ssc.SaveZaml = false;

	ImageEncoderType encoder = ImageEncoderType.JpegBitmap;

	switch (type)
	{
		case "png":
			encoder = ImageEncoderType.PngBitmap;
			break;
		case "jpeg":
			encoder = ImageEncoderType.JpegBitmap;
			break;
	}

	ssc.EncoderType = encoder;
	ssc.SaveXaml = false;

	using (MemoryStream svgStream = new MemoryStream(svg))
	{
		TextReader svgData = new StreamReader(svgStream);

		using (MemoryStream exportObjectStream = new MemoryStream())
		{
			ssc.Convert(svgData, exportObjectStream);

			return exportObjectStream;
		}
	}
}
```

This is actually working fine with those servers which have not been updated with recent windows updates. In my system also it was working fine. But after windows update is has stopped working. So I took the code snippet and created a sample web forms which calls the same code and executed in visual studio. It is working fine. But if I host the application, It is not working.

**Comment by paulushub** [comment]
Thanks, I will look into it. One Jason Schulman also reported the same or similar issue. He followed up and provided this link below. I will try to reproduce the problem and look for a way to solve it.

https://support.microsoft.com/en-us/help/4043601/rendering-issues-after-the-september-12-2017-net-security-and-quality

**Comment by Anoop1001** [comment]
Thank you very much.

**Comment by Anoop1001** [comment]
Tried with the link provided. It did not work. Most of the updates are already existing.

**Comment by paulushub** [comment]
According to Microsoft docs, WPF and GDI+ are not designed to work in such environments.
An alternative rendering will be provided for such cases, This issue cannot be resolved!
