### ISSUE TITLE
Cursor always "Arrow" for SvgViewbox

### ISSUE THREAD

**Issue by sebastianlau** [ElinamLLC/SharpVectors#60]
No matter what styling is applied (in a resource dictionary, inline, trigger, etc) the child SvgDrawingCanvas always ends up with a local instance of Cursor = Arrow

**Comment by paulushub** [comment]
A working hit-test support is provided.

**Comment by EMWorksTunisie** [comment]
What can I do to fix this bug?

**Comment by paulushub** [comment]
@EMWorksTunisie I have just turned off the current cursor handling in the committed code. See if this works for you.
