### ISSUE TITLE
Can not convert this svg file.

### ISSUE THREAD

**Issue by JasonGrass** [ElinamLLC/SharpVectors#68]
Hello, I found the following svg file cannot convert to xaml(WPF) correctly.   
[browserstack_logo.zip](https://github.com/ElinamLLC/SharpVectors/files/2334307/browserstack_logo.zip)

![image](https://user-images.githubusercontent.com/10756994/44824672-83412c80-ac39-11e8-89b3-df296f42e34d.png)

![image](https://user-images.githubusercontent.com/10756994/44824695-9c49dd80-ac39-11e8-9101-0b5360b898fa.png)

**Comment by paulushub** [comment]
@JasonGrass Sorry for the delay, this issue is not resolved and committed (9f45403ffacc63546de7ae7c91a33ed721ec1681).
It was due to bugs in opacity mask implementations.

**Comment by JasonGrass** [comment]
THANKS~
