### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by ravenpride** [ElinamLLC/SharpVectors#69]
I'd like to know, whether this project follows the rules for [semantic versioning](https://semver.org/). It would make decisions concerning updates much easier as the version number indicates whether there was a breaking change, a new feature that did not break compatibility or just a patch fixing an issue. Based on this other developers can build NuGet packages that allow depending on a range of versions, not just a fixed one.

**Comment by paulushub** [comment]
It is largely following the semantic versioning, which is really consistent with the .NET versioning. 
I personally prefer using the revision number (4th) to indicate the date of release like 1.1.0.20180904, but will use that for the applications not the libraries.
So far, we have not really broken any application in the update, the DLL name changes was for the following reasons (the namespaces remained the same)
* Consistency with the other DLLs (Wpf or Gdi to indicate the rendering engine).
* There is a need to develop the current GDI+ rendering to the level of the WPF, which is currently not working well in web applications.
* With the GDI+ will also come other immediate mode rendering engines, especially Google SKIA.

The current library is really old, with parts written about 10 years ago, there is a need to clean up and modernize parts, but so far the interfaces are not affected.

**Comment by paulushub** [comment]
Right, for now there is no need to change interfaces since the efforts will be on rendering. Hopefully, version 2.x will introduce scripting and there might be some compatibility issues.
