### ISSUE TITLE
Loading svg via FileSvgReader creates unnecessary border

### ISSUE THREAD

**Issue by sepiel** [ElinamLLC/SharpVectors#70]
Hello,

when loading a svg file via the FileSvgReader this creates a bounding rectangle around the loaded image. But this behavior should not be intended.

**Comment by paulushub** [comment]
@sepiel Please post a picture to show what you mean.

**Comment by sepiel** [comment]
Following picture shows a border around the warning sign (svg image), that shouldn't be there. The "old" library doesn't show this behavior.

![borderaroundwarningsign](https://user-images.githubusercontent.com/42858881/45074776-0a345000-b0e5-11e8-8278-487833d9a010.PNG)

**Comment by paulushub** [comment]
@sepiel Thanks for the update. 
Please can you share the source SVG file with me (privately, if necessary), so that I can examine the issue?

**Comment by sepiel** [comment]
The following text file contains the information for the used svg:
[Sign_StatusWarning.txt](https://github.com/ElinamLLC/SharpVectors/files/2352641/Sign_StatusWarning.txt)

**Comment by paulushub** [comment]
@sepiel Sorry, the attached sample could not demonstrate the issue or I am missing something? Attached is the output image.
![sign_statuswarning txt](https://user-images.githubusercontent.com/809351/45100946-5d4de780-b165-11e8-84cc-4f1b8bd9107e.png)

**Comment by sepiel** [comment]
@paulushub I investigated on my own and found out that the svg is loaded correctly without a border. In my project i recolorize the image and this produces the border. Although the svg consists of only one path describing the object, the loaded image consists of two parts which seems to produces a border when getting recolorized. I added a test project visualizing this behavior, you can find this under following URL:

[https://github.com/sepiel/SvgReader.SharpVectors.Reloaded.Test](url)

Hope his helps.

**Comment by paulushub** [comment]
@sepiel OK, I get the source of the issue. It is due to the patch submitted months ago and I did not see any problem or effects.

**Fixed not saving original image size** (https://github.com/ElinamLLC/SharpVectors/commit/a981afe1bdbc6db6fd309ea65d5fc749cf2e0373)

If there is any need, I could add options to enable/disable the feature; drawing the boundary of the viewbox but with transparent color. 
For your case, you can simply exclude changing the color of transparent brushes:
```csharp
private static void ChangeColor(Brush brush, Color color)
{
    if (brush is SolidColorBrush)
    {
        SolidColorBrush scb = brush as SolidColorBrush;
        if (scb.Color.Equals(Colors.Transparent))
        {
            return; // PAUL!
        }
        scb.Color = color;
    }
    else
    {
        Debug.Fail("Brush type not supported.");
    }
}
```

**Comment by sepiel** [comment]
@paulushub Thanks for your answer. Your proposed changes solve my problem.
