### ISSUE TITLE
Bug in SetClip (WpfRendering)

### ISSUE THREAD

**Issue by wischi-chr** [ElinamLLC/SharpVectors#79]
I tried to load and show an svg in wpf and it crashed with a NullReferenceException, after downloading the source I figured out that it happens right here:

https://github.com/ElinamLLC/SharpVectors/blob/58127c92e5926b795cdc47c8f8d5b26780c490b3/Source/SharpVectorRenderingWpf/Wpf/WpfRendering.cs#L289

`if (overflow != null || overflow.CssText == "")`

I'm not familiar with the source but this condition seems to be wrong.

Maybe it should look like that?
`if (overflow != null && overflow.CssText != "")`

or that:

`if (!string.IsNullOrEmpty(overflow?.CssText))`

**Comment by paulushub** [comment]
Thanks for the fix, I will update the source soon.

**Comment by wischi-chr** [comment]
Thanks for maintaining this awsome library

**Comment by paulushub** [comment]
@wischi-chr This issue is resolved in 46017007eaf2410336c05fe5a8964615a20c6b45. 
Please confirm it.
Thanks for the sample SVG file, it helped fixed another issue (not reported).

**Comment by wischi-chr** [comment]
@paulushub tested it right now - works great.

_Thank you._
