### ISSUE TITLE
Feature request: string to Image.

### ISSUE THREAD

**Issue by Jerajo** [ElinamLLC/SharpVectors#80]
I would like to convert an string to a image without reading a .svg file.

**Example**
```C#
            // 1. Create conversion options
            WpfDrawingSettings settings = new WpfDrawingSettings();
            settings.IncludeRuntime = true;
            settings.TextAsGeometry = false;

            // 2. Text to convert
            string textToConvert = "Hello World!!";

            // 3. Create a file reader
            StreamSvgConverter converter = new StreamSvgConverter(settings);
            // 4. convert the SVG file
            MemoryStream memStream = new MemoryStream();

            if (converter.Convert(textToConvert, memStream))
            {
                BitmapImage bitmap = new BitmapImage();
                bitmap.BeginInit();
                bitmap.CacheOption = BitmapCacheOption.OnLoad;
                bitmap.StreamSource = memStream;
                bitmap.EndInit();
                // Set the image source.
                svgImage.Source = bitmap;
            }

            memStream.Close();
```

**Comment by paulushub** [comment]
All the converters have a method that accepts `TextReader` as parameter. So use any of the converters that meets you needs with 

`StringReader svgTextReader = new StringReader(new StringBuilder(textToConvert));`

Having both file paths and file contents as parameters to methods with multiple overloads is confusing. The readers and writers are designed for such cases and handle the contents.

**Comment by Jerajo** [comment]
**The new feature is to convert normal text to Images without using files.**

--------------

**Code**

```C#
...
string textToConvert = "Hello, World_ ";
converter.Convert(textToConvert);
...
```

--------------

**Output**

![imagen](https://user-images.githubusercontent.com/26252994/48463340-10643e00-e7b2-11e8-803f-7a757a832baa.png)

**Comment by paulushub** [comment]
This library only converts SVG format text. You can use `StringBuilder` or `XmlTextWriter` to build your text into SVG format and add the necessary styling to it.

```csharp
StringBuilder builder = new StringBuilder("<svg xmlns=\"http://www.w3.org/2000/svg\">");
builder.AppendLine("<text x=\"250\" y=\"150\" font-family=\"Verdana\" font-size=\"55\" fill=\"green\">");
builder.AppendLine("Hello, World_");
builder.AppendLine("</text>");
builder.AppendLine("</svg>");
```
