### ISSUE TITLE
Mouse Click on DOM Element

### ISSUE THREAD

**Issue by doczoidberg** [ElinamLLC/SharpVectors#81]
Is it possible to get the node which is clicked in the svg and to get it's attributes?

**Comment by paulushub** [comment]
@doczoidberg The rendered drawing is WPF object. You can hit test these objects but they are not linked to the SVG objects. The IDs of SVG objects are assigned as names to the WPF objects.
You can search for the corresponding SVG object where a valid ID is assigned, valid HTML ids are not necessarily valid WPF name and may be changed.

**Comment by doczoidberg** [comment]
I save a simple file in inkscape. IDs are not converted to the name:


```
<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   width="210mm"
   height="297mm"
   viewBox="0 0 210 297"
   version="1.1"
   id="svg8"
   inkscape:version="0.92.2 (5c3e80d, 2017-08-06)"
   sodipodi:docname="inkscape-rectangle.svg">
  <defs
     id="defs2" />
  <sodipodi:namedview
     id="base"
     pagecolor="#ffffff"
     bordercolor="#666666"
     borderopacity="1.0"
     inkscape:pageopacity="0.0"
     inkscape:pageshadow="2"
     inkscape:zoom="0.35"
     inkscape:cx="-224.28571"
     inkscape:cy="560"
     inkscape:document-units="mm"
     inkscape:current-layer="layer1"
     showgrid="false"
     inkscape:window-width="1920"
     inkscape:window-height="1027"
     inkscape:window-x="-8"
     inkscape:window-y="-8"
     inkscape:window-maximized="1" />
  <metadata
     id="metadata5">
    <rdf:RDF>
      <cc:Work
         rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        <dc:title></dc:title>
      </cc:Work>
    </rdf:RDF>
  </metadata>
  <g
     inkscape:label="Ebene 1"
     inkscape:groupmode="layer"
     id="layer1">
    <rect
       style="fill:#007aff;fill-opacity:1;stroke:#0a79fd;stroke-width:1.86500001;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"
       id="rect815"
       width="84.666664"
       height="38.55357"
       x="86.178574"
       y="77.773804" />
  </g>
</svg>
```
XAML:
```
<DrawingGroup xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
  <DrawingGroup x:Name="DrawingLayer">
    <DrawingGroup.ClipGeometry>
      <RectangleGeometry Rect="0,0,210,297" />
    </DrawingGroup.ClipGeometry>
    <DrawingGroup x:Name="layer1" Opacity="1">
      <GeometryDrawing Brush="#FF007AFF">
        <GeometryDrawing.Pen>
          <Pen Brush="#FF0A79FD" Thickness="1.86500001" StartLineCap="Flat" EndLineCap="Flat" LineJoin="Miter" />
        </GeometryDrawing.Pen>
        <GeometryDrawing.Geometry>
          <RectangleGeometry RadiusX="0" RadiusY="0" Rect="86.1786,77.7738,84.6667,38.5536" />
        </GeometryDrawing.Geometry>
      </GeometryDrawing>
    </DrawingGroup>
  </DrawingGroup>
</DrawingGroup>
```

**Comment by paulushub** [comment]
It is a bit tricky! Geometry cannot be named in WPF. The available options are using Shapes or the custom ID through the SharpVectors runtime, giving you something like  `svg:SvgObject.Id="layer1`".

Shape rendering is not completely supported yet, purposely delay to complete one WPF rendering and then duplicate the codes.

**Comment by paulushub** [comment]
Sorry, this is a bug introduced in the last update. To improve the path rendering. Output should be the following
```xml
<DrawingGroup xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:svg="http://sharpvectors.codeplex.com/runtime/">
  <DrawingGroup x:Name="DrawingLayer" svg:SvgLink.Key="DrawingLayer">
    <DrawingGroup.ClipGeometry>
      <RectangleGeometry Rect="0,0,210,297" />
    </DrawingGroup.ClipGeometry>
    <DrawingGroup x:Name="layer1" Opacity="1" svg:SvgObject.Id="layer1">
      <GeometryDrawing x:Name="rect815" Brush="#FF007AFF" svg:SvgObject.Id="rect815">
        <GeometryDrawing.Pen>
          <Pen Brush="#FF0A79FD" Thickness="1.86500001" StartLineCap="Flat" EndLineCap="Flat" LineJoin="Miter" />
        </GeometryDrawing.Pen>
        <GeometryDrawing.Geometry>
          <RectangleGeometry RadiusX="0" RadiusY="0" Rect="86.1786,77.7738,84.6667,38.5536" />
        </GeometryDrawing.Geometry>
      </GeometryDrawing>
    </DrawingGroup>
  </DrawingGroup>
</DrawingGroup>
```

**Comment by paulushub** [comment]
@doczoidberg I have just committed the fix, please check with the latest version. Sorry for the inconvenience.

**Comment by doczoidberg** [comment]
@paulushub works now. thanks, great work!

**Comment by cr4nk89** [comment]
I know this does not belong under this issue, but this the most accurate topic to my question when googling click events. Maybe this helps others, too.

 Can you explain how you get the XAML ID?

My XAML:
` <svg:SvgDrawingCanvas x:Name="svgDrawing" Background="Transparent" MouseLeftButtonDown="canvas_MouseLeftButtonDown">
                    </svg:SvgDrawingCanvas>`
My XAML.CS:
`        private void canvas_MouseLeftButtonDown(object sender, MouseButtonEventArgs e)
        { }`

I just can't find any XAML Information in my object sender or MouseButtonEventArgs e. Is there something missing in my XAML code?

**Comment by doczoidberg** [comment]
you have to case the sender to the xaml object and read the name

**Comment by cr4nk89** [comment]
DrawingGroup does not contain Name, but I can do
`(sender as SharpVectors.Runtime.SvgDrawingCanvas).Name`
which results in always returning my x:Name"svgDrawing"

I can see ~400 child objects. Seems to be correct, but I cant get the clicked one. Is there something I have to link with the XAML code? Somekind of Binding=twoway like in grid?

**Comment by paulushub** [comment]
@cr4nk89 Please read my first comment on this thread. You will need to hit test to get the target drawing. There are on hit tests codes in the SvgDrawingCanvas source, which was originally designed for a special viewing case.

**Comment by dolanor** [comment]
For reference (since I just looked for it):
https://github.com/ElinamLLC/SharpVectors/blob/ff7f8829680714853f4ee4846fb420eb36e97b57/Source/SharpVectorRuntimeWpf/SvgDrawingCanvas.cs#L423
https://github.com/ElinamLLC/SharpVectors/blob/ff7f8829680714853f4ee4846fb420eb36e97b57/Source/SharpVectorRuntimeWpf/SvgDrawingCanvas.cs#L903-L1181
