### ISSUE TITLE
Please add Databinding

### ISSUE THREAD

**Issue by Worker3** [ElinamLLC/SharpVectors#82]
When using a dynamic List of items with associated svg-Image Path, it would be nice to do the following binding (or similiar or with SvgViewbox):

<Image Source="{svgc:SvgImage Source={Binding SVGImagePath}}" />

I am not sure howto achieve this, the error Message tells something about DependencyProperty and DependencyObject.

**Comment by paulushub** [comment]
Do you need it in the image source extension used as below?

```<Image Source="{svgc:SvgImage /Images/NotThere.svg}"/>```

**Comment by paulushub** [comment]
I have resolved this issue by adding a new image source extension, `SvgImageConverter`. The source is committed as 808e0910e675b69c5ad1afbf45b843d86765cddc.
You can find demo sample at `TutorialSamples\ControlSamplesWpf\SvgImageBindingSample`.

Please check and confirm this.

**Comment by Worker3** [comment]
Thank you for the very fast(!) help :)
It works very good for absolute paths, relative ones are not supported, yet (?), but that would be a nice to have thing. I can basically do what I want now. Thx again
this code was used:
`Source="{Binding Path=SVGImagePath, Converter={svgc:SvgImageConverter}}"`

**Comment by paulushub** [comment]
Thanks for feedback. I thought it works with relative paths too. Please give an example of path that fails (and location of the svg file).
Also, if you have a simple demo project, you can attach the zip file so that I could investigate the issue.

**Comment by paulushub** [comment]
@Worker3 Thanks for the feedback. Issue now resolved with c7ab67c44e812324aeae85cf917e5c432ccd9589.

**Comment by Worker3** [comment]
Great work! 
Thanks
