### ISSUE TITLE
Show no Image when Path is not pointing to an existing file

### ISSUE THREAD

**Issue by Worker3** [ElinamLLC/SharpVectors#83]
The WPF Application throws an exception and crashes, if there is no svg file found at the source path.
Thats bad. It should behave like the normal Image Element, which simple displays no Image on a missing file.

`<Image Source="{svgc:SvgImage /Images/NotThere.svg}"/>`

> An unhandled exception of type 'System.Windows.Markup.XamlParseException' occurred in PresentationFramework.dll
> Additional information: Zeilennummer "109" und Zeilenposition "74" von "Die Angabe eines Werts für "SharpVectors.Converters.SvgImageExtension" führte zu einer Ausnahme.".

**Comment by paulushub** [comment]
This is an extension which catches exception during design, so the best way is to throw it in runtime. 
If you not see the image during the design process, but decide to ignore it, then you will get the exception, which is a fair action :)

**Comment by Worker3** [comment]
If I deploy my (Desktop-)Application and one svg is missing, the whole application cannot start. I think thats not fair ;)
Since there is also text, a missing Image wouldn't stop the user from working with the program.

**Comment by paulushub** [comment]
This issue is now resolved in 3e2cab247308fe70733f664f8f1b60353ed7458e and source committed. 
Please check and confirm it.

**Comment by Worker3** [comment]
It displays a white Image instead of crashing now, that's really nice, thx.
