### ISSUE TITLE
SvgViewbox doesn't show ToolTip

### ISSUE THREAD

**Issue by Kozinaka** [ElinamLLC/SharpVectors#87]
SvgViewbox doesn't show ToolTip and hide tooltip of parent control.
To show tooltips I have to use this hack:
```
<Grid>
    <svgc:SvgViewbox Source="..." ToolTip="This tooltip won't be shown"/>
    <Border Background="Transparent"  ToolTip="Hack for show this tooltip"/>
</Grid>
```

**Comment by paulushub** [comment]
The tooltip text is now passed onto the contained SvgDrawingCanvas and will be displayed. 
Please verify this fix: 2867765874b339afa0f3bfe4787e4df2e2f87fdc

**Comment by Kozinaka** [comment]
Yeah! Thank you! It works now!
This way works too:
```
<Button ToolTip="Parent button tooltip">
    <svgc:SvgViewbox Source="..."/>
</Button>
```

**Comment by paulushub** [comment]
@Kozinaka Thanks for verifying it. 

BTW, for icons or button images, you may consider `SvgImage` and `SvgImageConverter` extension classes. Please see the `SvgImageSample` and `SvgImageBindingSample` samples under `TutorialSamples\ControlSamples`
