### ISSUE TITLE
Make SvgDrawingCanvas Drawings public

### ISSUE THREAD

**Issue by dojo90** [ElinamLLC/SharpVectors#88]
Actually I want to change the color of the svg via XAML or code behind. Due to the `private` modifier, it is not possible to access the objects (see: https://github.com/ElinamLLC/SharpVectors/blob/master/Source/SharpVectorRuntimeWpf/SvgDrawingCanvas.cs#L49).

I found a possibility to get it working via reflection:

```
SvgDrawingCanvas canvas = (SvgDrawingCanvas) foo.Child;
List<Drawing> drawings = (List<Drawing>)typeof(SvgDrawingCanvas).GetField("_drawObjects", BindingFlags.NonPublic | BindingFlags.Instance).GetValue(canvas);

foreach (Drawing drawing in drawings)
{
	if (drawing is GeometryDrawing geometryDrawing)
	{
		geometryDrawing.Brush = Brushes.BlueViolet;
	}
}
```

Is there a special reason why they are `private`?

**Comment by paulushub** [comment]
SvgDrawingCanvas is based on an initial work for a customer, before the library was made public. That is why most parts are commented out.
The Runtime classes and the controls like SvgViewbox needs a lot more improvements to be more useful and I have these on my TODO, just trying to improve the conversion process first for now.

Now, what is the actual requirements of your project? Do you need the SvgDrawingCanvas? SvgDrawingCanvas is only useful if you separate the processes; conversion and viewing. The initial requirement for a car wiring manual, converts all the SVG files to XAML files and combine with documentations/instructions in FlowDocument XAML to create an interactive WPF-based manual. So the SvgDrawingCanvas was for the viewing application at the end-users, the conversion library was not shipped to the end-users; only the Runtime library.
For most other projects, the controls might be more useful so if you do not mind can you state the actual requirements?

**Comment by dojo90** [comment]
I think it's great that you bring the library back to life and continue to develop!

In my project I have a plant visualization! From SolidWorks I can export individual modules as SVG. This makes it possible to implement the layout 1: 1 in my C # application without much effort.

Since it is also possible to select individual stations, I have to color my modules. Therefore, I need access to the individual elements of the SVG.

---

In detail I have a `Grid` and two `SvgViewbox`. The background svg is the part of the module which I color. 

```XAML
<Grid>
	<svgc:SvgViewbox x:Name="backgroundSvg" Source="4H040339_bg.svg"/>
	<svgc:SvgViewbox x:Name="svg"  Source="4H040339.svg"/>
</Grid>
```

![2019-02-12 13_33_22-window](https://user-images.githubusercontent.com/17551597/52772385-a3727580-3038-11e9-98ff-b65659c03218.png)

![svg](https://user-images.githubusercontent.com/17551597/52772675-665ab300-3039-11e9-9dc6-98a9065b8ef6.gif)

---

As an additional improovement would be to get acces to a named layer inside of the svg. So I could have 2 layer inside of my svg and only color the "background_layer". This could save me a `SvgViewbox`.

**Comment by paulushub** [comment]
Thanks for the compliments, happy to know this library is useful to your works.

> Therefore, I need access to the individual elements of the SVG.

Will modify the controls to allow access to the loaded SVG document, will drop the use of converter classes in the controls.
I have being looking for a simple way to let developers use the Element visitor to make modifications in the SVG document at runtime, maybe through a dependency injection. 

> So I could have 2 layer inside of my svg and only color the "background_layer".

You can loop through the drawings in the DrawingGroup to find the background_layer. Layers are converted to DrawingGroup in the drawings.

> It would be amazing if it is possible to let the `Threadpool` make a conversion between `svg` and `xaml`.

The library does not impose any application framework, the SvgDrawingCanvas does not handle conversions, these are handled by the SvgConverter derived classes. The converter classes can be ran in a different thread and even in different .NET domain.

The controls such as SvgViewbox and SvgCanvas do handle conversions, so we could support background conversion here including support for async/await procedures in .NET45 versions.

Just for information, do you have animations in the SVG files?

**Comment by dojo90** [comment]
> Will modify the controls to allow access to the loaded SVG document, will drop the use of converter classes in the controls.
I have being looking for a simple way to let developers use the Element visitor to make modifications in the SVG document at runtime, maybe through a dependency injection.

I do not understand exactly what you want to tell me

> You can loop through the drawings in the DrawingGroup to find the background_layer. Layers are converted to DrawingGroup in the drawings.
Ah ok! I have found another way to solve my problem with only 1 svg and without any layers. The `GeometryDrawing.Brush` property is the background of the `path` in the svg. So in default I have a transparant background and the contour is black. So if I modify the `GeometryDrawing.Brush` property, the background gets changed. 

I wonder just if it is also possible to specify the contour, since currently only the background (of the svg) is bound to the `GeometryDrawing.Brush` property.

> The controls such as SvgViewbox and SvgCanvas do handle conversions, so we could support background conversion here including support for async/await procedures in .NET45 versions.

That's a good solution! Then the gui would be much more response! Actually I have more than 4seconds until the Page has been loaded..

> Just for information, do you have animations in the SVG files?

It is very simple. I made a `Binding` in code behind between a public `DependencyProperty` of the `customControl` and `BrushProperty`. Then in my XAML Style definition, I have a `Storyboard` to animate the `DependencyProperty`
```csharp
foreach (Drawing drawing in drawings)
{
	if (drawing is GeometryDrawing geometryDrawing)
	{
		BindingOperations.SetBinding(geometryDrawing, GeometryDrawing.BrushProperty, fillBinding);
	}
}
```

**Comment by paulushub** [comment]
>I do not understand exactly what you want to tell me

I think we need more documentations of the library features since mode is being added. Basically, you can modify the SVG DOM if the Svg Document object is exposed. It is an instance of XmlDocument, so you can query, modify etc.
The statement is how to make it useful for developers using the controls in their applications.

> Ah ok! I have found another way to solve my problem with only 1 svg and without any layers.

Personally, I think the layer could make the work clearer. Design tools allow layer creation so the flow will be natural.

> It is very simple. I made a `Binding` in code behind between a public `DependencyProperty` of the...

You only need more access to the created Drawing objects, will commit those changes soon.

**Comment by paulushub** [comment]
@dojo90 Please see if this commit addresses your needs 6eec55531b23d76a9fc3ebf1b3b1511e0cbe2ee4

**Comment by dojo90** [comment]
> I think we need more documentations of the library features since mode is being added. Basically, you can modify the SVG DOM if the Svg Document object is exposed. It is an instance of XmlDocument, so you can query, modify etc.

But that means you have to 'redraw'/'render' the svg after modifing the source. For my personal needs, it's enough to get access to each object of the rendered svg. Maybe other people want to modify the svg via their app. With your last commit https://github.com/ElinamLLC/SharpVectors/commit/6eec55531b23d76a9fc3ebf1b3b1511e0cbe2ee4 a developer has access to all the rendered objects. That is exactly what I was asking for 😎 👍

> I just wonder if it is also possible to specify the contour, since currently only the background (of the svg) is bound to the `GeometryDrawing.Brush` property.

Could you please take a look at this quote

**Comment by CorsairRO** [comment]
Hello and thank you for sharing such a nice library with us...

I need a library like this to use in my WPF applications.

However I have some questions ...

0) My goal is to Load / Store some SVG files in the database, and give the user the possibility to change them. I do not care at all about xaml and other stuff.

I need just to be able to:
- Show a SVG Image ( I can do this by using one of your controls )
- Allow User to Add some shapes to the screen and move them around by mouse
- Save his changes back to database.
- I don't care anything about any xaml conversion or something else like this.

My app is WPF.

1) SVGCanvas and SVGDrawingCanvas

What is the difference?
None of them works like a real canvas, because I tried to add some lines to the Children property and it didn't show up, while in the normal WPF Canvas it works.
If I understood wrong what a canvas should be, please let me know, or if you have some other suggestions will be very appreciated.

2) Like somebody else pointed out earlier in the thread, please make all the properties public so that we do not need reflection to access them.

Also, some properties are not accessbile at all, as they are created on the fly and never stored anywhere.
Examples are: SVGImage, and all the manipulation of drawings / groups and so on.

For this, I tried the reflection to get the drawings rendered, and trying to add something to that collection.
Now, question is: What do I do to show them onto the screen.

3) In the same area, I found a Winforms old Library for SVG that holds a reference to the SVG Dom, and expose it publicly, while the rendered stuff is a GDI Image. Working over the image updates accordingly the SVg DOM.
THis sounded like an interesting idea to follow, but in your library here I cannot find any place to access the Loaded SVG DOM. 

Do I need to save/load in a FILE every time that it is manipulated?

Thank you for your answrers,
Have a nice day.

**Comment by paulushub** [comment]
@CorsairRO Please repost your issue in different thread. If this issue is closed, your post will be closed too.

**Comment by Lak4CYUT** [comment]
> It is very simple. I made a `Binding` in code behind between a public `DependencyProperty` of the `customControl` and `BrushProperty`. Then in my XAML Style definition, I have a `Storyboard` to animate the `DependencyProperty`
> 
> ```cs
> foreach (Drawing drawing in drawings)
> {
> 	if (drawing is GeometryDrawing geometryDrawing)
> 	{
> 		BindingOperations.SetBinding(geometryDrawing, GeometryDrawing.BrushProperty, fillBinding);
> 	}
> }
> ```

@dojo90 Hi, I am looking for a way to change svg foreground color and I just saw your solution in here.
Thanks for your idea, it is help me a lot, but I don't really understand how to bind a non-DependencyProperty to my ViewModel (Child? Drawings?).
I can access SvgViewbox via x:Name but I will more like to access it with ViewModel (MVVM), could you please give me more hint? Thanks.

**Comment by Lak4CYUT** [comment]
After a couple research, I found my solution. It is reference to @dojo90 's sample code, but it don't need to add code on code-behind. Just create a custom dependency property and bind it.
```
    public class MySvgViewbox : SvgViewbox
    {
        public static readonly DependencyProperty BrushProperty = 
            DependencyProperty.Register("Brush", typeof(Brush), 
                typeof(MySvgViewbox), new PropertyMetadata(
                    Brushes.BlueViolet));

        public Brush Brush
        {
            get { return (Brush)GetValue(BrushProperty); }
            set { SetValue(BrushProperty, value); }
        }

        protected override void OnSettingsChanged()
        {
            base.OnSettingsChanged();
            IList<Drawing> drawings = ((SvgDrawingCanvas)Child).DrawObjects;
            foreach (Drawing drawing in drawings)
            {
                if (drawing is GeometryDrawing geometryDrawing)
                {
                    Binding b = new Binding("Brush")
                    {
                        Source = this,
                        Mode = BindingMode.OneWay
                    };
                    BindingOperations.SetBinding(geometryDrawing, GeometryDrawing.BrushProperty, b);
                }
            }
        }
    }
```

**Comment by stojy** [comment]
Sorry to reserruct this issue, but is there a plan to include this feature into SvgViewbox?

If so, you might find the folllowing implementation useful as it also allows for overriding the svg's stroke color.

```
    public class SvgViewboxEx : SvgViewbox
    {
        public static readonly DependencyProperty FillProperty = DependencyProperty.Register("Fill", typeof(Brush), typeof(SvgViewboxEx), new PropertyMetadata(Brushes.BlueViolet));

        public static readonly DependencyProperty StrokeProperty = DependencyProperty.Register("Stroke", typeof(Brush), typeof(SvgViewboxEx), new PropertyMetadata(Brushes.DarkViolet));

        public Brush Fill
        {
            get => (Brush) GetValue(FillProperty);
            set => SetValue(FillProperty, value);
        }

        public Brush Stroke
        {
            get => (Brush) GetValue(StrokeProperty);
            set => SetValue(StrokeProperty, value);
        }

        protected override void OnSettingsChanged()
        {
            base.OnSettingsChanged();

            var drawings = ((SvgDrawingCanvas) Child).DrawObjects;

            foreach (var drawing in drawings)
            {
                if (drawing is GeometryDrawing geometryDrawing)
                {
                    // svg fill color - translated to a geometry.Brush
                    var brush = new Binding(nameof(Fill))
                                    {
                                        Source = this,
                                        Mode = BindingMode.OneWay
                                    };
                    BindingOperations.SetBinding(geometryDrawing, GeometryDrawing.BrushProperty, brush);

                    // svg stroke color - translated to a geometry.Pen.Brush
                    if (geometryDrawing.Pen != null)
                    {
                        var stroke = new Binding(nameof(Stroke))
                                         {
                                             Source = this,
                                             Mode = BindingMode.OneWay
                                         };
                        BindingOperations.SetBinding(geometryDrawing.Pen, Pen.BrushProperty, stroke);
                    }
                }
            }
        }
    }
```

**Comment by paulushub** [comment]
@stojy Do you mean the binding operations suggested by @Lak4CYUT?
The original thread was on making the drawing in `SvgDrawingCanvas` public, which really is not an issue since `SvgDrawingCanvas` does not perform conversion by itself. 
So, @Lak4CYUT post should be in a different thread to be addressed properly.

You can post a new issue with your suggestions and reference this one. 
This is similar to the discussion here [Change svg image colors at runtime?](https://github.com/ElinamLLC/SharpVectors/discussions/163).

**Comment by stojy** [comment]
@paulushub, that's correct.. I was referring to @Lak4CYUT's binding suggestion.  I'll make a fresh posting as suggested.
