### ISSUE TITLE
IOException: Resource not found if used in external library

### ISSUE THREAD

**Issue by dojo90** [ElinamLLC/SharpVectors#89]
I got a library `framework.dll` and an `application.exe`. Inside of the `framework` is a class `CustomClass` which uses the `SvgViewbox` in its `xaml` template.

The `CustomClass` got a `DependencyProperty` of type `Uri` which is bound to the `SvgViewbox.Source` in its template.

The used `custom.svg` is declared as `Resource` in the `application.exe`. Now during design time, everything works and the `custom.svg` is correctly displayed. If I run the application, the `SvgViewbox` is unable to find the `svg` because it is looking in `farmework.dll` .

---

Is there a way to solve this problem without adding a "application.exe\" prefix at the `DependencyProperty`?

---

Actually my "quick&dirty" solution

```csharp
    public class ApplicationResourcePrefixConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            if (value is Uri uri && uri.OriginalString is string s)
            {
                if (!s.Contains(";component/"))
                {
                    s = s.Replace("../", ""); // remove directory movement if where in sub-directory
                    s = $"/{Assembly.GetEntryAssembly().GetName().Name};component/{s}";
                    return s;
                }                
            }
            return value;
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            throw new NotImplementedException();
        }
    }
```

**Comment by paulushub** [comment]
How are you specifying the URI to the source property (does it include the external assembly name)?

Read this reference on the Pack Uri used by the WPF
[Pack URIs in WPF](https://docs.microsoft.com/en-us/dotnet/framework/wpf/app-development/pack-uris-in-wpf)

**Comment by dojo90** [comment]
I have two scenarios:

1. `framework.dll` and `customer.exe`
1. `framework.dll`, `customerFramework.dll` and `customer.exe`

The `CustomClass` is part of `framework.dll` and this control can be placed in the `customerFramework.dll` or in `customer.exe` (in a `xaml page/window`). If I want use the `intelliSense` (of visualStudio), I need to declare the `Source` as below. The second benefit is the possibility of seeing the svg during the `designTime`. But if I run the `customer.exe`, my `CustomClass` as not able to find the `svg` because it is declared relative in the `customerFramework.dll` or `customer.exe`. So to get it also working in runtime, I need this little 'hack'

`Source="../Layout/P17-000984/StationModels/svg/4H040339.svg" `

**Comment by paulushub** [comment]
We have finally resolved this issue with the current update to the repository.
