### ISSUE TITLE
Only one svg is rendered when several controls has same svg radio button.

### ISSUE THREAD

**Issue by AllenShen1** [ElinamLLC/SharpVectors#91]
I've a wpf project contains a control which has two radio button 
<UserControl>
     <RadioButton x:Name="List" Content="{StaticResource Icon_Grid}" IsChecked="False" Style=" 
           {DynamicResource RadioButtonStyle1}" />
     <RadioButton x:Name="Grid" Content="{StaticResource Icon_List}" IsChecked="True" Style=" 
           {DynamicResource RadioButtonStyle1}" />
</UserControl>

And the Icon_Grid and Icon_List are SvgViewbox:

<svgc:SvgViewbox x:Key="Icon_Grid"  Stretch="None" Source="/ZZ.Micro.LL.Resources;component/NewIcons/Undefined.svg" />
    <svgc:SvgViewbox x:Key="Icon_List"  Stretch="None" Source="/ZZ.Micro.LL.Resources;component/NewIcons/Undefined.svg" />

After put 2 or 3 user controls on UI, Only the last user control are rendered successfully. The other's icon is empty

My expect result are all 2-3 user controls should be render succesfully

After I change the SvgViewbox to  "WPF Path", all the user controls are rendered successfully.

And I tried Button instead of RadioButton, this issue doesn't happen. It looks only affect the radio button.

My Platform is windows 10, with Quardo M2000M graphic card.

**Comment by dojo90** [comment]
I have more than 5 `SvgViewbox` instances with same resource without any problems. Did you set your svg as `Resource` ?

![grafik](https://user-images.githubusercontent.com/17551597/53016187-4833ef00-344d-11e9-9f85-30f5b423b584.png)

Preview
---
![grafik](https://user-images.githubusercontent.com/17551597/53016429-ee7ff480-344d-11e9-8118-9e3c13e9eaa0.png)

**Comment by paulushub** [comment]
@AllenShen1 For icons, you will typically use `SvgImage` and `SvgImageConverter` extension classes. Please see the `SvgImageSample` and `SvgImageBindingSample` samples under `TutorialSamples\ControlSamples`.

@dojo90 Thank you.
@AllenShen1 If you are still having a problem, then post a working sample for reference.

**Comment by AllenShen1** [comment]
I still have the same problem， I refered the controlssample, but no improvement.
I've changed the item like below:
<svgc:SvgViewbox x:Key="Icon_Grid" Stretch="None" Source="/ZZ.Micro.Labscope.Resources;component/NewIcons/Undefined.svg" />
to 
<Image x:Key="Icon_Upload" Stretch="None" Source="{svgc:SvgImage Source=/ZZ.Micro.Labscope.Resources;component/NewIcons/Undefined.svg}"/>

![image](https://user-images.githubusercontent.com/47772603/53221734-b246d100-36a5-11e9-82b2-91272e8bee72.png)

**Comment by paulushub** [comment]
@AllenShen1 Please create a sample project, zip it and attach it to this post so that I can take a look.

**Comment by AllenShen1** [comment]
> I have more than 5 `SvgViewbox` instances with same resource without any problems. Did you set your svg as `Resource` ?
> 
> ![grafik](https://user-images.githubusercontent.com/17551597/53016187-4833ef00-344d-11e9-9f85-30f5b423b584.png)
> 
> ## Preview
> ![grafik](https://user-images.githubusercontent.com/17551597/53016429-ee7ff480-344d-11e9-8118-9e3c13e9eaa0.png)

Yes, it's resource of course, these 4 icons share same one. Only one is shown.
