### ISSUE TITLE
Styles rendering issue

### ISSUE THREAD

**Issue by Mikolaytis** [ElinamLLC/SharpVectors#93]
Hi. I have next svg:
`<svg id="Layer_1" x="0px" y="0px" viewBox="0 0 64 64" style="enable-background:new 0 0 64 64;">
    <style>
      .st0{fill:#FAEFDE;}
      .st1{fill:#EFD8BE;}
      .st2{fill:#F9DD8F;}
      .st3{fill:#CDA1A7;}
      .st4{fill:#8D6C9F;}
      .st5{fill:#BBDEF9;}
      .st6{fill:#ED7899;}
    </style>
    <g>
        <polygon fill="#FAEFDE" points="52,33 31,13 7,33 7,57 55,57 " />
        <path class="st1" d="M31,13L7,33v1.7c0,1.1,0.9,2,2,2c0.5,0,0.9-0.2,1.3-0.5l20.1-16.7c0.4-0.3,0.9-0.3,1.3,0l20.1,16.7 c0.8,0.7,2.1,0.6,2.8-0.3c0.3-0.4,0.5-0.8,0.5-1.3V33L31,13z" />
        <rect x="7" y="47" class="st2" width="48" height="10" />
        <path class="st3" d="M31.6,13.5l25.7,21.1c0.4,0.3,1.1,0.3,1.4-0.1c0.1-0.2,0.2-0.4,0.2-0.6V31c0-0.6-0.3-1.2-0.7-1.5L32.3,8 c-0.7-0.6-1.8-0.6-2.5,0l-26,21.4C3.3,29.8,3,30.3,3,31v2.9c0,0.6,0.5,1,1,1c0.2,0,0.4-0.1,0.6-0.2l25.7-21.1 C30.7,13.2,31.3,13.2,31.6,13.5z" />
        <path class="st4" d="M16,50c-0.6,0-1,0.4-1,1v2c0,0.6,0.4,1,1,1c0.6,0,1-0.4,1-1v-2C17,50.4,16.6,50,16,50z" />
        <path class="st4" d="M11,50c-0.6,0-1,0.4-1,1v2c0,0.6,0.4,1,1,1s1-0.4,1-1v-2C12,50.4,11.6,50,11,50z" />
        <path class="st4" d="M46,50c-0.6,0-1,0.4-1,1v2c0,0.6,0.4,1,1,1s1-0.4,1-1v-2C47,50.4,46.6,50,46,50z" />
        <path class="st4" d="M51,50c-0.6,0-1,0.4-1,1v2c0,0.6,0.4,1,1,1s1-0.4,1-1v-2C52,50.4,51.6,50,51,50z" />
        <circle class="st5" cx="31" cy="24" r="4" />
        <path class="st4" d="M31,19c-2.8,0-5,2.2-5,5s2.2,5,5,5s5-2.2,5-5S33.8,19,31,19z M31,27.2c-1.8,0-3.2-1.4-3.2-3.2s1.4-3.2,3.2-3.2 c1.8,0,3.2,1.4,3.2,3.2v0C34.2,25.8,32.8,27.2,31,27.2z" />
        <rect x="25" y="37" class="st6" width="12" height="20" />
        <path class="st4" d="M33,45c-0.6,0-1,0.4-1,1v2c0,0.6,0.4,1,1,1s1-0.4,1-1v-2C34,45.4,33.6,45,33,45z" />
        <path class="st4" d="M56.7,35.4c0.9,0.7,2.1,0.6,2.8-0.3c0.3-0.4,0.5-0.8,0.5-1.3V31c0-0.9-0.4-1.8-1.1-2.3l-26-21.4 c-1.1-0.9-2.7-0.9-3.8,0L18,16.4v-3.3c0-0.6-0.4-1-1-1s-1,0.4-1,1v5l-2,1.6V9.1c0-0.6-0.4-1-1-1s-1,0.4-1,1v12c0,0.1,0,0.1,0,0.2 l-8.9,7.4C2.4,29.2,2,30.1,2,31v2.9c0,0.8,0.4,1.5,1.2,1.8c0.7,0.3,1.5,0.2,2.1-0.3L6,34.8V56H3c-0.6,0-1,0.4-1,1s0.4,1,1,1h56 c0.6,0,1-0.4,1-1s-0.4-1-1-1h-3V34.8L56.7,35.4z M22,56h-2H8v-8h16v8H22z M26,56V38h10v18H26z M54,56H42h-2h-2v-8h16V56z M54,38v8 H38v-8c0-1.1-0.9-2-2-2H26c-1.1,0-2,0.9-2,2v8H8v-8v-4.8l23-18.9l23,18.9V38z M32.3,12.8c-0.7-0.6-1.8-0.6-2.5,0L4,33.9V31 c0-0.3,0.1-0.6,0.4-0.8l26-21.4c0.4-0.3,0.9-0.3,1.3,0l26,21.4c0.2,0.2,0.4,0.5,0.4,0.8v2.9L32.3,12.8z" />
        <path class="st4" d="M21,50c-0.6,0-1,0.4-1,1v2c0,0.6,0.4,1,1,1s1-0.4,1-1v-2C22,50.4,21.6,50,21,50z" />
        <path class="st4" d="M41,50c-0.6,0-1,0.4-1,1v2c0,0.6,0.4,1,1,1s1-0.4,1-1v-2C42,50.4,41.6,50,41,50z" />
    </g>
</svg>`

It's renders full black, not accepting style colors :(

**Comment by Mikolaytis** [comment]
fix is to add xmlns="http://www.w3.org/2000/svg" to svg....

**Comment by paulushub** [comment]
If you view the file in any browser, you will get the message

> This XML file does not appear to have any style information associated with it.

For such complex file (embedding styling sheet), you need the svg namespace for correct parsing.
