### ISSUE TITLE
Next Nuget Release, SvgImageBinding

### ISSUE THREAD

**Issue by LLambertRGi** [ElinamLLC/SharpVectors#97]
Hi, I'd like to be able to use the features present in the `SvgImageBindingSample`, binding an SVG source to an image, but it's not included in the current Nuget release. Would it be possible to push a new release to Nuget?

**Comment by paulushub** [comment]
@LLambertRGi Sorry, the I did not realize we have enough features to merit a release! I am so much focused on supporting SVG fonts (just to pass more of the specifications tests!).

I will create a new release Version 1.3 this weekend. It should be ready for download by Monday (maybe Sunday depending on your location - Japan is few hours ahead of other countries).
Now, the control used in that sample, `SvgImageConverter`, was added based on a user request #82. Does this currently meets your needs (looking at the demo sample)?

**Comment by paulushub** [comment]
Version 1.3 is now published.
