### ISSUE TITLE
ScientificToDec should allow leading sign

### ISSUE THREAD

**Issue by Beregoz** [ElinamLLC/SharpVectors#98]
SvgNumber.cs

 var numberValue = decimal.Parse(value,
                    NumberStyles.AllowExponent | NumberStyles.AllowDecimalPoint **| NumberStyles.AllowLeadingSign**, CultureInfo.InvariantCulture);

Without the fix the parsing fails with exception if the input value starts with leading sign like "-2.0".

**Comment by paulushub** [comment]
Sorry, missed this one - thanks for investigating this.
